<?php
/**
 * Archive: Resources
 * This is essentially the resource library — same as template-resources.php
 * but auto-generated by WordPress for /resources/ URL.
 */
get_header(); ?>

<div class="hero hero--short">
    <div class="container">
        <div class="hero__content">
            <span class="hero__eyebrow"><?php esc_html_e( 'Tools for Organizing', 'faithfulwitness' ); ?></span>
            <h1><?php esc_html_e( 'Resource Library', 'faithfulwitness' ); ?></h1>
        </div>
    </div>
</div>

<section class="section resources-library">
    <div class="container">

        <div class="resources-toolbar" id="resources-toolbar">
            <div class="resources-toolbar__search">
                <input type="search" id="resource-search" class="form-control" placeholder="<?php esc_attr_e( 'Search resources…', 'faithfulwitness' ); ?>">
            </div>
            <div class="resources-toolbar__filters" role="group">
                <button class="filter-pill active" data-filter-type="type" data-value="" aria-pressed="true"><?php esc_html_e( 'All Types', 'faithfulwitness' ); ?></button>
                <?php
                $types = get_terms( [ 'taxonomy' => 'fw_resource_type', 'hide_empty' => true ] );
                if ( $types && ! is_wp_error( $types ) ) :
                    foreach ( $types as $t ) :
                ?>
                    <button class="filter-pill" data-filter-type="type" data-value="<?php echo esc_attr( $t->slug ); ?>" aria-pressed="false">
                        <?php echo esc_html( $t->name ); ?> <span class="filter-pill__count"><?php echo esc_html( $t->count ); ?></span>
                    </button>
                <?php endforeach; endif; ?>
            </div>
            <div class="resources-toolbar__initiative-filter">
                <select id="initiative-filter" class="form-control" data-filter-type="initiative">
                    <option value=""><?php esc_html_e( 'All Initiatives', 'faithfulwitness' ); ?></option>
                    <?php
                    $inits = get_terms( [ 'taxonomy' => 'fw_initiative_category', 'hide_empty' => true ] );
                    if ( $inits && ! is_wp_error( $inits ) ) :
                        foreach ( $inits as $i ) :
                    ?>
                        <option value="<?php echo esc_attr( $i->term_id ); ?>"><?php echo esc_html( $i->name ); ?></option>
                    <?php endforeach; endif; ?>
                </select>
            </div>
        </div>

        <div class="grid grid--auto resources-grid" id="resources-grid">
            <?php if ( have_posts() ) :
                while ( have_posts() ) : the_post();
                    fw_render_resource_card( $post );
                endwhile;
            endif; ?>
        </div>

        <div class="resources-no-results" id="resources-no-results" style="display:none;text-align:center;padding:3rem 0;">
            <p style="font-size:var(--text-xl);color:var(--color-text-muted);"><?php esc_html_e( 'No resources match your search.', 'faithfulwitness' ); ?></p>
            <button id="reset-all-filters" class="btn btn--outline" style="margin-top:1rem;"><?php esc_html_e( 'Reset Filters', 'faithfulwitness' ); ?></button>
        </div>

        <?php the_posts_pagination( [ 'class' => 'pagination' ] ); ?>
    </div>
</section>

<?php get_footer();
