<?php
/**
 * ACF Field Group Definitions — Faithful Witness
 *
 * These definitions run only when Advanced Custom Fields (free or Pro)
 * is installed and active. They replace the native meta boxes with a
 * cleaner, instruction-rich admin form.
 *
 * When ACF is NOT installed, the existing native meta boxes in
 * inc/meta-boxes.php are used as a fallback — all meta key names are
 * identical so the front-end templates work in both cases.
 *
 * ADMIN NOTE: Do not edit this file. All content is managed via the
 * WordPress admin forms. If you need to add a new field, contact your
 * developer.
 */

if ( ! defined( 'ABSPATH' ) ) exit;

/**
 * Register all field groups once ACF is ready.
 */
add_action( 'acf/init', 'fw_register_acf_fields' );
function fw_register_acf_fields() {
    if ( ! function_exists( 'acf_add_local_field_group' ) ) return;

    fw_acf_group_resources();
    fw_acf_group_media_hits();
    fw_acf_group_organizing_groups();
    fw_acf_group_stories();
    fw_acf_options_homepage();
}

// ============================================================
// RESOURCES — fw_resource
// ============================================================
function fw_acf_group_resources() {
    acf_add_local_field_group( [
        'key'    => 'group_fw_resource',
        'title'  => 'Resource Details',
        'fields' => [

            // ── CATEGORIZATION TAB ───────────────────────────────
            [
                'key'   => 'field_fw_res_tab_cat',
                'label' => 'Categorization',
                'type'  => 'tab',
            ],

            [
                'key'          => 'field_fw_resource_type_tax',
                'label'        => 'Resource Type',
                'name'         => 'fw_resource_type',
                'type'         => 'taxonomy',
                'instructions' => 'Choose the format of this resource — PDF, article, toolkit, etc.',
                'taxonomy'     => 'fw_resource_type',
                'field_type'   => 'select',
                'allow_null'   => 1,
                'return_format'=> 'id',
                'load_save_terms' => 1,
                'save_other_choice' => 0,
                'required'     => 0,
            ],

            [
                'key'          => 'field_fw_resource_issue_area',
                'label'        => 'Issue Area(s)',
                'name'         => 'fw_resource_issue_area',
                'type'         => 'taxonomy',
                'instructions' => 'Check all issue areas this resource addresses. Visitors will use these to filter the library.',
                'taxonomy'     => 'fw_resource_issue_area',
                'field_type'   => 'checkbox',
                'allow_null'   => 1,
                'return_format'=> 'id',
                'load_save_terms' => 1,
                'save_other_choice' => 0,
            ],

            [
                'key'          => 'field_fw_resource_audience',
                'label'        => 'Who Is This For?',
                'name'         => 'fw_resource_audience',
                'type'         => 'taxonomy',
                'instructions' => 'Check all groups this resource is intended for.',
                'taxonomy'     => 'fw_resource_audience',
                'field_type'   => 'checkbox',
                'allow_null'   => 1,
                'return_format'=> 'id',
                'load_save_terms' => 1,
                'save_other_choice' => 0,
            ],

            [
                'key'          => 'field_fw_related_initiative',
                'label'        => 'Campaign',
                'name'         => 'fw_related_initiative_id',
                'type'         => 'post_object',
                'instructions' => 'If this resource belongs to a specific campaign, select it here. It will appear in the "Resource Packs by Campaign" section on the library page. Leave blank if it is a general resource.',
                'post_type'    => [ 'fw_initiative' ],
                'taxonomy'     => '',
                'allow_null'   => 1,
                'multiple'     => 0,
                'return_format'=> 'id',
                'required'     => 0,
            ],

            [
                'key'          => 'field_fw_resource_featured',
                'label'        => 'Featured Resource',
                'name'         => 'fw_resource_featured',
                'type'         => 'true_false',
                'instructions' => 'Toggle ON to feature this resource in the "Start Here" section at the very top of the Resource Library page. Only the 3 most recently featured resources are shown there.',
                'message'      => 'Feature this resource in the "Start Here" section',
                'default_value'=> 0,
                'ui'           => 1,
                'ui_on_text'   => 'Featured',
                'ui_off_text'  => 'Not featured',
            ],

            // ── DOWNLOAD / LINK TAB ──────────────────────────────
            [
                'key'   => 'field_fw_res_tab_link',
                'label' => 'Download or Link',
                'type'  => 'tab',
            ],

            [
                'key'          => 'field_fw_resource_file_id',
                'label'        => 'Upload File',
                'name'         => 'fw_resource_file_id',
                'type'         => 'file',
                'instructions' => 'Upload a PDF, Word doc, or other file here. Visitors will see a download button on the resource card. If you have a Google Drive link instead, leave this empty and paste the link in "External Link" below.',
                'return_format'=> 'id',
                'library'      => 'all',
                'required'     => 0,
            ],

            [
                'key'          => 'field_fw_resource_url',
                'label'        => 'External Link',
                'name'         => 'fw_resource_url',
                'type'         => 'url',
                'instructions' => 'Paste a full URL here (e.g. a Google Drive link, YouTube video, or external web page). Only use this if you are NOT uploading a file above. If both are filled in, the file upload takes priority.',
                'required'     => 0,
            ],

            [
                'key'           => 'field_fw_resource_button_label',
                'label'         => 'Button Label',
                'name'          => 'fw_resource_button_label',
                'type'          => 'text',
                'instructions'  => 'The text shown on the resource\'s download/access button. Change this to match the content — e.g. "Read Article", "Watch Video", "Download Guide". Default: "Download Resource".',
                'default_value' => 'Download Resource',
                'placeholder'   => 'Download Resource',
                'required'      => 0,
            ],

        ],
        'location' => [
            [ [ 'param' => 'post_type', 'operator' => '==', 'value' => 'fw_resource' ] ],
        ],
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'field',
        'hide_on_screen'        => [
            'the_content',
            'discussion',
            'comments',
            'revisions',
            'slug',
            'author',
            'format',
            'tags',
            'send-trackbacks',
        ],
    ] );
}

// ============================================================
// MEDIA HITS — fw_media_hit
// ============================================================
function fw_acf_group_media_hits() {
    acf_add_local_field_group( [
        'key'    => 'group_fw_media_hit',
        'title'  => 'Article Details',
        'fields' => [

            [
                'key'          => 'field_fw_media_outlet',
                'label'        => 'Outlet Name',
                'name'         => 'fw_media_outlet',
                'type'         => 'text',
                'instructions' => 'The name of the news outlet or publication — e.g. "Christianity Today", "Religion News Service".',
                'placeholder'  => 'e.g. Christianity Today',
                'required'     => 1,
            ],

            [
                'key'          => 'field_fw_media_url',
                'label'        => 'Article URL',
                'name'         => 'fw_media_url',
                'type'         => 'url',
                'instructions' => 'Paste the full URL to the article including https://. The article headline will become a clickable link to that page.',
                'required'     => 0,
            ],

            [
                'key'            => 'field_fw_media_pub_date',
                'label'          => 'Publication Date',
                'name'           => 'fw_media_pub_date',
                'type'           => 'date_picker',
                'instructions'   => 'The date the article was published. Press coverage is displayed in reverse-chronological order.',
                'display_format' => 'F j, Y',
                'return_format'  => 'Y-m-d',
                'first_day'      => 0,
                'required'       => 0,
            ],

            [
                'key'          => 'field_fw_media_pull_quote',
                'label'        => 'Pull Quote or Excerpt',
                'name'         => 'fw_media_pull_quote',
                'type'         => 'textarea',
                'instructions' => 'Copy a compelling sentence or two from the article to display on the press card. Use quotation marks to show it is a direct quote. Keep it under 30 words.',
                'rows'         => 3,
                'new_lines'    => '',
                'required'     => 0,
            ],

            [
                'key'          => 'field_fw_media_outlet_logo',
                'label'        => 'Outlet Logo',
                'name'         => 'fw_media_outlet_logo_url',
                'type'         => 'image',
                'instructions' => 'Upload the outlet\'s logo (optional). This displays in the top-left of the press card. Use a PNG with transparent background if possible. If no logo is uploaded, the outlet name is shown as text instead.',
                'return_format'=> 'url',
                'library'      => 'all',
                'min_width'    => 0,
                'min_height'   => 0,
                'required'     => 0,
            ],

        ],
        'location' => [
            [ [ 'param' => 'post_type', 'operator' => '==', 'value' => 'fw_media_hit' ] ],
        ],
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'field',
        'hide_on_screen'        => [
            'the_content',
            'discussion',
            'comments',
            'revisions',
            'slug',
            'author',
            'format',
            'tags',
            'send-trackbacks',
        ],
    ] );
}

// ============================================================
// ORGANIZING GROUPS / PARTNERS — fw_organizing_group
// ============================================================
function fw_acf_group_organizing_groups() {
    acf_add_local_field_group( [
        'key'    => 'group_fw_organizing_group',
        'title'  => 'Organization Details',
        'fields' => [

            // ── LOCATION TAB ─────────────────────────────────────
            [
                'key'   => 'field_fw_og_tab_location',
                'label' => 'Location',
                'type'  => 'tab',
            ],

            [
                'key'         => 'field_fw_og_city',
                'label'       => 'City',
                'name'        => 'fw_city',
                'type'        => 'text',
                'instructions'=> 'The city where this organization is based, or "National" for national organizations.',
                'placeholder' => 'e.g. Chicago',
                'required'    => 0,
                'wrapper'     => [ 'width' => '50' ],
            ],

            [
                'key'         => 'field_fw_og_state',
                'label'       => 'State',
                'name'        => 'fw_state_abbr',
                'type'        => 'text',
                'instructions'=> 'Two-letter state abbreviation, e.g. IL for Illinois.',
                'placeholder' => 'e.g. IL',
                'required'    => 0,
                'wrapper'     => [ 'width' => '50' ],
            ],

            [
                'key'         => 'field_fw_og_lat',
                'label'       => 'Map Latitude',
                'name'        => 'fw_lat',
                'type'        => 'number',
                'instructions'=> 'To find coordinates: go to maps.google.com, right-click the organization\'s location on the map, and click the numbers that appear at the top of the menu. Paste the first number (latitude) here.',
                'placeholder' => 'e.g. 41.8781',
                'step'        => 'any',
                'required'    => 0,
                'wrapper'     => [ 'width' => '50' ],
            ],

            [
                'key'         => 'field_fw_og_lng',
                'label'       => 'Map Longitude',
                'name'        => 'fw_lng',
                'type'        => 'number',
                'instructions'=> 'Paste the second number from the Google Maps coordinates here (the longitude — it will be negative for most US locations).',
                'placeholder' => 'e.g. -87.6298',
                'step'        => 'any',
                'required'    => 0,
                'wrapper'     => [ 'width' => '50' ],
            ],

            // ── CONTACT TAB ──────────────────────────────────────
            [
                'key'   => 'field_fw_og_tab_contact',
                'label' => 'Contact & Links',
                'type'  => 'tab',
            ],

            [
                'key'         => 'field_fw_og_website',
                'label'       => 'Website URL',
                'name'        => 'fw_website_url',
                'type'        => 'url',
                'instructions'=> 'The organization\'s main website. Include https://.',
                'placeholder' => 'https://',
                'required'    => 0,
            ],

            [
                'key'         => 'field_fw_og_email',
                'label'       => 'Contact Email',
                'name'        => 'fw_contact_email',
                'type'        => 'email',
                'instructions'=> 'A public contact email for this organization.',
                'required'    => 0,
                'wrapper'     => [ 'width' => '50' ],
            ],

            [
                'key'         => 'field_fw_og_phone',
                'label'       => 'Contact Phone',
                'name'        => 'fw_contact_phone',
                'type'        => 'text',
                'instructions'=> 'A public phone number for this organization (optional).',
                'placeholder' => 'e.g. (312) 555-0100',
                'required'    => 0,
                'wrapper'     => [ 'width' => '50' ],
            ],

            [
                'key'         => 'field_fw_og_instagram',
                'label'       => 'Instagram URL',
                'name'        => 'fw_instagram_url',
                'type'        => 'url',
                'instructions'=> 'Full Instagram profile URL, e.g. https://instagram.com/orgname',
                'required'    => 0,
                'wrapper'     => [ 'width' => '50' ],
            ],

            [
                'key'         => 'field_fw_og_facebook',
                'label'       => 'Facebook URL',
                'name'        => 'fw_facebook_url',
                'type'        => 'url',
                'required'    => 0,
                'wrapper'     => [ 'width' => '50' ],
            ],

            [
                'key'         => 'field_fw_og_twitter',
                'label'       => 'Twitter / X URL',
                'name'        => 'fw_twitter_url',
                'type'        => 'url',
                'required'    => 0,
                'wrapper'     => [ 'width' => '50' ],
            ],

            // ── TYPE TAB ─────────────────────────────────────────
            [
                'key'   => 'field_fw_og_tab_type',
                'label' => 'Organization Type',
                'type'  => 'tab',
            ],

            [
                'key'          => 'field_fw_og_org_type',
                'label'        => 'Partner Type',
                'name'         => 'fw_org_type',
                'type'         => 'select',
                'instructions' => 'Choose the type that best describes this organization. This determines the pin color on the network map: Navy = National Partner, Amber = Local Church, Teal = Organizing Group.',
                'choices'      => [
                    'national-partner' => 'National Partner',
                    'local-church'     => 'Local Church',
                    'organizing-group' => 'Organizing Group',
                ],
                'default_value'=> 'national-partner',
                'allow_null'   => 0,
                'return_format'=> 'value',
            ],

            [
                'key'          => 'field_fw_og_focus_areas',
                'label'        => 'Focus Areas',
                'name'         => 'fw_og_focus_areas',
                'type'         => 'taxonomy',
                'instructions' => 'Select all issue areas this organization focuses on. These appear as tags on the partner card.',
                'taxonomy'     => 'fw_resource_issue_area',
                'field_type'   => 'checkbox',
                'allow_null'   => 1,
                'return_format'=> 'id',
                'load_save_terms' => 1,
                'save_other_choice' => 0,
            ],

        ],
        'location' => [
            [ [ 'param' => 'post_type', 'operator' => '==', 'value' => 'fw_organizing_group' ] ],
        ],
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'field',
    ] );
}

// ============================================================
// STORIES — WP posts (Story Type = blog posts)
// ============================================================
function fw_acf_group_stories() {
    acf_add_local_field_group( [
        'key'    => 'group_fw_story',
        'title'  => 'Story Details',
        'fields' => [

            [
                'key'          => 'field_fw_story_author_name',
                'label'        => 'Author Name',
                'name'         => 'fw_story_author_name',
                'type'         => 'text',
                'instructions' => 'The person\'s name as you want it to appear on the story — e.g. "Rev. Maria Santos" or "Anonymous". Leave blank to use the WordPress user account name.',
                'placeholder'  => 'e.g. Rev. Maria Santos',
                'required'     => 0,
                'wrapper'      => [ 'width' => '50' ],
            ],

            [
                'key'          => 'field_fw_story_author_church',
                'label'        => 'Church or Organization',
                'name'         => 'fw_story_author_church',
                'type'         => 'text',
                'instructions' => 'The author\'s church or organization affiliation — e.g. "Lakeview Community Church" or "World Relief Chicago".',
                'placeholder'  => 'e.g. Lakeview Community Church',
                'required'     => 0,
                'wrapper'      => [ 'width' => '50' ],
            ],

            [
                'key'          => 'field_fw_story_city',
                'label'        => 'City',
                'name'         => 'fw_story_city',
                'type'         => 'text',
                'instructions' => 'The author\'s city — shown below their name on the story card.',
                'placeholder'  => 'e.g. Chicago, IL',
                'required'     => 0,
                'wrapper'      => [ 'width' => '50' ],
            ],

        ],
        'location' => [
            [ [
                'param'    => 'post_type',
                'operator' => '==',
                'value'    => 'post',
            ] ],
        ],
        'menu_order'            => 20,
        'position'              => 'side',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'field',
    ] );
}

// ============================================================
// ACF OPTIONS PAGE — Homepage Settings
// ============================================================
function fw_acf_options_homepage() {
    if ( ! function_exists( 'acf_add_options_page' ) ) return;

    acf_add_options_sub_page( [
        'page_title'  => 'Homepage Settings',
        'menu_title'  => 'Homepage Settings',
        'parent_slug' => 'faithfulwitness-hub',
        'capability'  => 'edit_posts',
        'redirect'    => false,
    ] );

    acf_add_local_field_group( [
        'key'    => 'group_fw_homepage_options',
        'title'  => 'Homepage Settings',
        'fields' => [

            // ── CAMPAIGN SECTION ─────────────────────────────────
            [
                'key'   => 'field_fw_hp_tab_campaign',
                'label' => 'Campaign Highlight',
                'type'  => 'tab',
            ],

            [
                'key'           => 'field_fw_campaign_headline',
                'label'         => 'Campaign Headline',
                'name'          => 'fw_campaign_headline',
                'type'          => 'text',
                'instructions'  => 'The bold headline shown in the campaign highlight section on the homepage. Keep it under 8 words.',
                'default_value' => 'Stand With Immigrant Families',
                'placeholder'   => 'e.g. Stand With Immigrant Families',
            ],

            [
                'key'           => 'field_fw_campaign_description',
                'label'         => 'Campaign Description',
                'name'          => 'fw_campaign_description',
                'type'          => 'textarea',
                'instructions'  => 'A short description of the current campaign — 1-2 sentences shown under the headline. Keep it concise and action-oriented.',
                'rows'          => 3,
                'new_lines'     => '',
                'default_value' => 'The moment calls for faithful witnesses to speak and act with courage. Join churches across the country in this critical campaign.',
            ],

            [
                'key'           => 'field_fw_campaign_cta_label',
                'label'         => 'Button Label',
                'name'          => 'fw_campaign_cta_label',
                'type'          => 'text',
                'instructions'  => 'The text on the action button in the campaign section.',
                'default_value' => 'Take Action',
                'wrapper'       => [ 'width' => '50' ],
            ],

            [
                'key'           => 'field_fw_campaign_cta_url',
                'label'         => 'Button URL',
                'name'          => 'fw_campaign_cta_url',
                'type'          => 'url',
                'instructions'  => 'Where the action button links to. Can be an internal page like /take-action or an external URL.',
                'wrapper'       => [ 'width' => '50' ],
            ],

            // ── PARTNER LOGOS ────────────────────────────────────
            [
                'key'   => 'field_fw_hp_tab_partners',
                'label' => 'Partner Logos',
                'type'  => 'tab',
            ],

            [
                'key'          => 'field_fw_partner1_name',
                'label'        => 'Partner 1 — Name',
                'name'         => 'fw_partner1_name',
                'type'         => 'text',
                'default_value'=> 'NaLEC',
                'wrapper'      => [ 'width' => '33' ],
            ],
            [
                'key'          => 'field_fw_partner1_logo',
                'label'        => 'Partner 1 — Logo',
                'name'         => 'fw_partner1_logo_url',
                'type'         => 'image',
                'return_format'=> 'url',
                'instructions' => 'Upload a logo image (PNG preferred). Displayed at about 80px tall.',
                'wrapper'      => [ 'width' => '33' ],
            ],
            [
                'key'          => 'field_fw_partner1_url',
                'label'        => 'Partner 1 — Website',
                'name'         => 'fw_partner1_url',
                'type'         => 'url',
                'default_value'=> 'https://nalec.org',
                'wrapper'      => [ 'width' => '33' ],
            ],

            [
                'key'          => 'field_fw_partner2_name',
                'label'        => 'Partner 2 — Name',
                'name'         => 'fw_partner2_name',
                'type'         => 'text',
                'default_value'=> 'CCDA',
                'wrapper'      => [ 'width' => '33' ],
            ],
            [
                'key'          => 'field_fw_partner2_logo',
                'label'        => 'Partner 2 — Logo',
                'name'         => 'fw_partner2_logo_url',
                'type'         => 'image',
                'return_format'=> 'url',
                'wrapper'      => [ 'width' => '33' ],
            ],
            [
                'key'          => 'field_fw_partner2_url',
                'label'        => 'Partner 2 — Website',
                'name'         => 'fw_partner2_url',
                'type'         => 'url',
                'default_value'=> 'https://ccda.org',
                'wrapper'      => [ 'width' => '33' ],
            ],

            [
                'key'          => 'field_fw_partner3_name',
                'label'        => 'Partner 3 — Name',
                'name'         => 'fw_partner3_name',
                'type'         => 'text',
                'default_value'=> 'World Relief',
                'wrapper'      => [ 'width' => '33' ],
            ],
            [
                'key'          => 'field_fw_partner3_logo',
                'label'        => 'Partner 3 — Logo',
                'name'         => 'fw_partner3_logo_url',
                'type'         => 'image',
                'return_format'=> 'url',
                'wrapper'      => [ 'width' => '33' ],
            ],
            [
                'key'          => 'field_fw_partner3_url',
                'label'        => 'Partner 3 — Website',
                'name'         => 'fw_partner3_url',
                'type'         => 'url',
                'default_value'=> 'https://worldrelief.org',
                'wrapper'      => [ 'width' => '33' ],
            ],

            [
                'key'          => 'field_fw_partner4_name',
                'label'        => 'Partner 4 — Name',
                'name'         => 'fw_partner4_name',
                'type'         => 'text',
                'default_value'=> 'Undivided',
                'wrapper'      => [ 'width' => '33' ],
            ],
            [
                'key'          => 'field_fw_partner4_logo',
                'label'        => 'Partner 4 — Logo',
                'name'         => 'fw_partner4_logo_url',
                'type'         => 'image',
                'return_format'=> 'url',
                'wrapper'      => [ 'width' => '33' ],
            ],
            [
                'key'          => 'field_fw_partner4_url',
                'label'        => 'Partner 4 — Website',
                'name'         => 'fw_partner4_url',
                'type'         => 'url',
                'default_value'=> 'https://undivided.us',
                'wrapper'      => [ 'width' => '33' ],
            ],

        ],
        'location' => [
            [ [ 'param' => 'options_page', 'operator' => '==', 'value' => 'acf-options-homepage-settings' ] ],
        ],
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'field',
    ] );
}

// ============================================================
// ACF NOTICE — prompt install if not present
// ============================================================
add_action( 'admin_notices', 'fw_acf_install_notice' );
function fw_acf_install_notice() {
    if ( function_exists( 'acf_add_local_field_group' ) ) return;
    if ( ! current_user_can( 'install_plugins' ) ) return;
    if ( get_option( 'fw_acf_notice_dismissed' ) ) return;

    $install_url = admin_url( 'plugin-install.php?s=advanced+custom+fields&tab=search&type=term' );
    ?>
    <div class="notice notice-info is-dismissible" id="fw-acf-notice">
        <p>
            <strong>Faithful Witness:</strong>
            For the best content editing experience, please
            <a href="<?php echo esc_url( $install_url ); ?>"><strong>install Advanced Custom Fields (free)</strong></a>.
            It adds clean, guided forms for adding resources, events, media hits, and partners.
            The site works without it, but the editing forms are much simpler with it.
        </p>
    </div>
    <script>
    document.addEventListener('DOMContentLoaded', function() {
        var n = document.getElementById('fw-acf-notice');
        if (!n) return;
        n.querySelector('.notice-dismiss') && n.querySelector('.notice-dismiss').addEventListener('click', function() {
            fetch('<?php echo esc_url( admin_url( 'admin-ajax.php' ) ); ?>', {
                method: 'POST',
                body: new URLSearchParams({ action: 'fw_dismiss_acf_notice', nonce: '<?php echo esc_js( wp_create_nonce( 'fw_dismiss_acf' ) ); ?>' }),
            });
        });
    });
    </script>
    <?php
}

add_action( 'wp_ajax_fw_dismiss_acf_notice', function () {
    check_ajax_referer( 'fw_dismiss_acf', 'nonce' );
    update_option( 'fw_acf_notice_dismissed', 1 );
    wp_send_json_success();
} );

// ============================================================
// RELABEL "Excerpt" → "Short Description" in editors
// ============================================================
add_action( 'admin_head', 'fw_relabel_excerpt' );
function fw_relabel_excerpt() {
    $screen = get_current_screen();
    if ( ! $screen ) return;
    if ( ! in_array( $screen->post_type, [ 'fw_resource', 'fw_organizing_group' ], true ) ) return;
    ?>
    <script>
    document.addEventListener('DOMContentLoaded', function() {
        var excerptLabel = document.querySelector('#postexcerpt h2, #postexcerpt .hndle');
        if (excerptLabel) excerptLabel.textContent = 'Short Description';
        var excerptHelp  = document.querySelector('#excerpt-fullscreen-save-wrapper, .editor-post-excerpt__title');
        if (excerptHelp) excerptHelp.textContent = 'Short Description';
    });
    </script>
    <?php
}
