<?php
/**
 * ACF Field Group Definitions — Faithful Witness
 *
 * These definitions run only when Advanced Custom Fields (free or Pro)
 * is installed and active. They replace the native meta boxes with a
 * cleaner, instruction-rich admin form.
 *
 * When ACF is NOT installed, the existing native meta boxes in
 * inc/meta-boxes.php are used as a fallback — all meta key names are
 * identical so the front-end templates work in both cases.
 *
 * ADMIN NOTE: Do not edit this file. All content is managed via the
 * WordPress admin forms. If you need to add a new field, contact your
 * developer.
 */

if ( ! defined( 'ABSPATH' ) ) exit;

/**
 * Register all field groups once ACF is ready.
 */
add_action( 'acf/init', 'fw_register_acf_fields' );
function fw_register_acf_fields() {
    if ( ! function_exists( 'acf_add_local_field_group' ) ) return;

    fw_acf_group_resources();
    fw_acf_group_media_hits();
    fw_acf_group_organizing_groups();
    fw_acf_group_stories();
    fw_acf_group_page_heroes();
    fw_acf_group_page_take_action();
    fw_acf_group_page_formation();
    fw_acf_group_page_kyr();
    fw_acf_group_support_entries();
    fw_acf_group_page_about();
    fw_acf_options_homepage();
}

// ============================================================
// RESOURCES — fw_resource
// ============================================================
function fw_acf_group_resources() {
    acf_add_local_field_group( [
        'key'    => 'group_fw_resource',
        'title'  => 'Resource Details',
        'fields' => [

            // ── CATEGORIZATION TAB ───────────────────────────────
            [
                'key'   => 'field_fw_res_tab_cat',
                'label' => 'Categorization',
                'type'  => 'tab',
            ],

            [
                'key'          => 'field_fw_resource_type_tax',
                'label'        => 'Resource Type',
                'name'         => 'fw_resource_type',
                'type'         => 'taxonomy',
                'instructions' => 'Choose the format of this resource — PDF, article, toolkit, etc.',
                'taxonomy'     => 'fw_resource_type',
                'field_type'   => 'select',
                'allow_null'   => 1,
                'return_format'=> 'id',
                'load_save_terms' => 1,
                'save_other_choice' => 0,
                'required'     => 0,
            ],

            [
                'key'          => 'field_fw_resource_issue_area',
                'label'        => 'Issue Area(s)',
                'name'         => 'fw_resource_issue_area',
                'type'         => 'taxonomy',
                'instructions' => 'Check all issue areas this resource addresses. Visitors will use these to filter the library.',
                'taxonomy'     => 'fw_resource_issue_area',
                'field_type'   => 'checkbox',
                'allow_null'   => 1,
                'return_format'=> 'id',
                'load_save_terms' => 1,
                'save_other_choice' => 0,
            ],

            [
                'key'          => 'field_fw_resource_audience',
                'label'        => 'Who Is This For?',
                'name'         => 'fw_resource_audience',
                'type'         => 'taxonomy',
                'instructions' => 'Check all groups this resource is intended for.',
                'taxonomy'     => 'fw_resource_audience',
                'field_type'   => 'checkbox',
                'allow_null'   => 1,
                'return_format'=> 'id',
                'load_save_terms' => 1,
                'save_other_choice' => 0,
            ],

            [
                'key'          => 'field_fw_related_initiative',
                'label'        => 'Campaign',
                'name'         => 'fw_related_initiative_id',
                'type'         => 'post_object',
                'instructions' => 'If this resource belongs to a specific campaign, select it here. It will appear in the "Resource Packs by Campaign" section on the library page. Leave blank if it is a general resource.',
                'post_type'    => [ 'fw_initiative' ],
                'taxonomy'     => '',
                'allow_null'   => 1,
                'multiple'     => 0,
                'return_format'=> 'id',
                'required'     => 0,
            ],

            [
                'key'          => 'field_fw_resource_featured',
                'label'        => 'Featured Resource',
                'name'         => 'fw_resource_featured',
                'type'         => 'true_false',
                'instructions' => 'Toggle ON to feature this resource in the "Start Here" section at the very top of the Resource Library page. Only the 3 most recently featured resources are shown there.',
                'message'      => 'Feature this resource in the "Start Here" section',
                'default_value'=> 0,
                'ui'           => 1,
                'ui_on_text'   => 'Featured',
                'ui_off_text'  => 'Not featured',
            ],

            // ── DOWNLOAD / LINK TAB ──────────────────────────────
            [
                'key'   => 'field_fw_res_tab_link',
                'label' => 'Download or Link',
                'type'  => 'tab',
            ],

            [
                'key'          => 'field_fw_resource_file_id',
                'label'        => 'Upload File',
                'name'         => 'fw_resource_file_id',
                'type'         => 'file',
                'instructions' => 'Upload a PDF, Word doc, or other file here. Visitors will see a download button on the resource card. If you have a Google Drive link instead, leave this empty and paste the link in "External Link" below.',
                'return_format'=> 'id',
                'library'      => 'all',
                'required'     => 0,
            ],

            [
                'key'          => 'field_fw_resource_url',
                'label'        => 'External Link',
                'name'         => 'fw_resource_url',
                'type'         => 'url',
                'instructions' => 'Paste a full URL here (e.g. a Google Drive link, YouTube video, or external web page). Only use this if you are NOT uploading a file above. If both are filled in, the file upload takes priority.',
                'required'     => 0,
            ],

            [
                'key'           => 'field_fw_resource_button_label',
                'label'         => 'Button Label',
                'name'          => 'fw_resource_button_label',
                'type'          => 'text',
                'instructions'  => 'The text shown on the resource\'s download/access button. Change this to match the content — e.g. "Read Article", "Watch Video", "Download Guide". Default: "Download Resource".',
                'default_value' => 'Download Resource',
                'placeholder'   => 'Download Resource',
                'required'      => 0,
            ],

        ],
        'location' => [
            [ [ 'param' => 'post_type', 'operator' => '==', 'value' => 'fw_resource' ] ],
        ],
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'field',
        'hide_on_screen'        => [
            'the_content',
            'discussion',
            'comments',
            'revisions',
            'slug',
            'author',
            'format',
            'tags',
            'send-trackbacks',
        ],
    ] );
}

// ============================================================
// MEDIA HITS — fw_media_hit
// ============================================================
function fw_acf_group_media_hits() {
    acf_add_local_field_group( [
        'key'    => 'group_fw_media_hit',
        'title'  => 'Article Details',
        'fields' => [

            [
                'key'          => 'field_fw_media_outlet',
                'label'        => 'Outlet Name',
                'name'         => 'fw_media_outlet',
                'type'         => 'text',
                'instructions' => 'The name of the news outlet or publication — e.g. "Christianity Today", "Religion News Service".',
                'placeholder'  => 'e.g. Christianity Today',
                'required'     => 1,
            ],

            [
                'key'          => 'field_fw_media_url',
                'label'        => 'Article URL',
                'name'         => 'fw_media_url',
                'type'         => 'url',
                'instructions' => 'Paste the full URL to the article including https://. The article headline will become a clickable link to that page.',
                'required'     => 0,
            ],

            [
                'key'            => 'field_fw_media_pub_date',
                'label'          => 'Publication Date',
                'name'           => 'fw_media_pub_date',
                'type'           => 'date_picker',
                'instructions'   => 'The date the article was published. Press coverage is displayed in reverse-chronological order.',
                'display_format' => 'F j, Y',
                'return_format'  => 'Y-m-d',
                'first_day'      => 0,
                'required'       => 0,
            ],

            [
                'key'          => 'field_fw_media_pull_quote',
                'label'        => 'Pull Quote or Excerpt',
                'name'         => 'fw_media_pull_quote',
                'type'         => 'textarea',
                'instructions' => 'Copy a compelling sentence or two from the article to display on the press card. Use quotation marks to show it is a direct quote. Keep it under 30 words.',
                'rows'         => 3,
                'new_lines'    => '',
                'required'     => 0,
            ],

            [
                'key'          => 'field_fw_media_outlet_logo',
                'label'        => 'Outlet Logo',
                'name'         => 'fw_media_outlet_logo_url',
                'type'         => 'image',
                'instructions' => 'Upload the outlet\'s logo (optional). This displays in the top-left of the press card. Use a PNG with transparent background if possible. If no logo is uploaded, the outlet name is shown as text instead.',
                'return_format'=> 'url',
                'library'      => 'all',
                'min_width'    => 0,
                'min_height'   => 0,
                'required'     => 0,
            ],

        ],
        'location' => [
            [ [ 'param' => 'post_type', 'operator' => '==', 'value' => 'fw_media_hit' ] ],
        ],
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'field',
        'hide_on_screen'        => [
            'the_content',
            'discussion',
            'comments',
            'revisions',
            'slug',
            'author',
            'format',
            'tags',
            'send-trackbacks',
        ],
    ] );
}

// ============================================================
// ORGANIZING GROUPS / PARTNERS — fw_organizing_group
// ============================================================
function fw_acf_group_organizing_groups() {
    acf_add_local_field_group( [
        'key'    => 'group_fw_organizing_group',
        'title'  => 'Organization Details',
        'fields' => [

            // ── LOCATION TAB ─────────────────────────────────────
            [
                'key'   => 'field_fw_og_tab_location',
                'label' => 'Location',
                'type'  => 'tab',
            ],

            [
                'key'         => 'field_fw_og_city',
                'label'       => 'City',
                'name'        => 'fw_city',
                'type'        => 'text',
                'instructions'=> 'The city where this organization is based, or "National" for national organizations.',
                'placeholder' => 'e.g. Chicago',
                'required'    => 0,
                'wrapper'     => [ 'width' => '50' ],
            ],

            [
                'key'         => 'field_fw_og_state',
                'label'       => 'State',
                'name'        => 'fw_state_abbr',
                'type'        => 'text',
                'instructions'=> 'Two-letter state abbreviation, e.g. IL for Illinois.',
                'placeholder' => 'e.g. IL',
                'required'    => 0,
                'wrapper'     => [ 'width' => '50' ],
            ],

            [
                'key'         => 'field_fw_og_lat',
                'label'       => 'Map Latitude',
                'name'        => 'fw_lat',
                'type'        => 'number',
                'instructions'=> 'To find coordinates: go to maps.google.com, right-click the organization\'s location on the map, and click the numbers that appear at the top of the menu. Paste the first number (latitude) here.',
                'placeholder' => 'e.g. 41.8781',
                'step'        => 'any',
                'required'    => 0,
                'wrapper'     => [ 'width' => '50' ],
            ],

            [
                'key'         => 'field_fw_og_lng',
                'label'       => 'Map Longitude',
                'name'        => 'fw_lng',
                'type'        => 'number',
                'instructions'=> 'Paste the second number from the Google Maps coordinates here (the longitude — it will be negative for most US locations).',
                'placeholder' => 'e.g. -87.6298',
                'step'        => 'any',
                'required'    => 0,
                'wrapper'     => [ 'width' => '50' ],
            ],

            // ── CONTACT TAB ──────────────────────────────────────
            [
                'key'   => 'field_fw_og_tab_contact',
                'label' => 'Contact & Links',
                'type'  => 'tab',
            ],

            [
                'key'         => 'field_fw_og_website',
                'label'       => 'Website URL',
                'name'        => 'fw_website_url',
                'type'        => 'url',
                'instructions'=> 'The organization\'s main website. Include https://.',
                'placeholder' => 'https://',
                'required'    => 0,
            ],

            [
                'key'         => 'field_fw_og_email',
                'label'       => 'Contact Email',
                'name'        => 'fw_contact_email',
                'type'        => 'email',
                'instructions'=> 'A public contact email for this organization.',
                'required'    => 0,
                'wrapper'     => [ 'width' => '50' ],
            ],

            [
                'key'         => 'field_fw_og_phone',
                'label'       => 'Contact Phone',
                'name'        => 'fw_contact_phone',
                'type'        => 'text',
                'instructions'=> 'A public phone number for this organization (optional).',
                'placeholder' => 'e.g. (312) 555-0100',
                'required'    => 0,
                'wrapper'     => [ 'width' => '50' ],
            ],

            [
                'key'         => 'field_fw_og_instagram',
                'label'       => 'Instagram URL',
                'name'        => 'fw_instagram_url',
                'type'        => 'url',
                'instructions'=> 'Full Instagram profile URL, e.g. https://instagram.com/orgname',
                'required'    => 0,
                'wrapper'     => [ 'width' => '50' ],
            ],

            [
                'key'         => 'field_fw_og_facebook',
                'label'       => 'Facebook URL',
                'name'        => 'fw_facebook_url',
                'type'        => 'url',
                'required'    => 0,
                'wrapper'     => [ 'width' => '50' ],
            ],

            [
                'key'         => 'field_fw_og_twitter',
                'label'       => 'Twitter / X URL',
                'name'        => 'fw_twitter_url',
                'type'        => 'url',
                'required'    => 0,
                'wrapper'     => [ 'width' => '50' ],
            ],

            // ── TYPE TAB ─────────────────────────────────────────
            [
                'key'   => 'field_fw_og_tab_type',
                'label' => 'Organization Type',
                'type'  => 'tab',
            ],

            [
                'key'          => 'field_fw_og_org_type',
                'label'        => 'Partner Type',
                'name'         => 'fw_org_type',
                'type'         => 'select',
                'instructions' => 'Choose the type that best describes this organization. This determines the pin color on the network map: Navy = National Partner, Amber = Local Church, Teal = Organizing Group.',
                'choices'      => [
                    'national-partner' => 'National Partner',
                    'local-church'     => 'Local Church',
                    'organizing-group' => 'Organizing Group',
                ],
                'default_value'=> 'national-partner',
                'allow_null'   => 0,
                'return_format'=> 'value',
            ],

            [
                'key'          => 'field_fw_og_focus_areas',
                'label'        => 'Focus Areas',
                'name'         => 'fw_og_focus_areas',
                'type'         => 'taxonomy',
                'instructions' => 'Select all issue areas this organization focuses on. These appear as tags on the partner card.',
                'taxonomy'     => 'fw_resource_issue_area',
                'field_type'   => 'checkbox',
                'allow_null'   => 1,
                'return_format'=> 'id',
                'load_save_terms' => 1,
                'save_other_choice' => 0,
            ],

        ],
        'location' => [
            [ [ 'param' => 'post_type', 'operator' => '==', 'value' => 'fw_organizing_group' ] ],
        ],
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'field',
    ] );
}

// ============================================================
// STORIES — WP posts (Story Type = blog posts)
// ============================================================
function fw_acf_group_stories() {
    acf_add_local_field_group( [
        'key'    => 'group_fw_story',
        'title'  => 'Story Details',
        'fields' => [

            [
                'key'          => 'field_fw_story_author_name',
                'label'        => 'Author Name',
                'name'         => 'fw_story_author_name',
                'type'         => 'text',
                'instructions' => 'The person\'s name as you want it to appear on the story — e.g. "Rev. Maria Santos" or "Anonymous". Leave blank to use the WordPress user account name.',
                'placeholder'  => 'e.g. Rev. Maria Santos',
                'required'     => 0,
                'wrapper'      => [ 'width' => '50' ],
            ],

            [
                'key'          => 'field_fw_story_author_church',
                'label'        => 'Church or Organization',
                'name'         => 'fw_story_author_church',
                'type'         => 'text',
                'instructions' => 'The author\'s church or organization affiliation — e.g. "Lakeview Community Church" or "World Relief Chicago".',
                'placeholder'  => 'e.g. Lakeview Community Church',
                'required'     => 0,
                'wrapper'      => [ 'width' => '50' ],
            ],

            [
                'key'          => 'field_fw_story_city',
                'label'        => 'City',
                'name'         => 'fw_story_city',
                'type'         => 'text',
                'instructions' => 'The author\'s city — shown below their name on the story card.',
                'placeholder'  => 'e.g. Chicago, IL',
                'required'     => 0,
                'wrapper'      => [ 'width' => '50' ],
            ],

        ],
        'location' => [
            [ [
                'param'    => 'post_type',
                'operator' => '==',
                'value'    => 'post',
            ] ],
        ],
        'menu_order'            => 20,
        'position'              => 'side',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'field',
    ] );
}

// ============================================================
// PAGE HEROES — shared eyebrow / title / subtitle / bg
// Attaches to every custom page template so editors can edit
// the hero banner directly on the page edit screen (ACF Free).
// ============================================================
function fw_acf_group_page_heroes() {
    acf_add_local_field_group( [
        'key'    => 'group_fw_page_hero',
        'title'  => 'Page Hero',
        'fields' => [
            [
                'key'          => 'field_fw_page_hero_eyebrow',
                'label'        => 'Eyebrow Label',
                'name'         => 'fw_page_hero_eyebrow',
                'type'         => 'text',
                'instructions' => 'Small label above the main headline. Keep it under 5 words.',
                'required'     => 0,
            ],
            [
                'key'          => 'field_fw_page_hero_title',
                'label'        => 'Hero Headline',
                'name'         => 'fw_page_hero_title',
                'type'         => 'text',
                'instructions' => 'Main H1 headline for this page. Leave blank to use the page title.',
                'required'     => 0,
            ],
            [
                'key'          => 'field_fw_page_hero_subtitle',
                'label'        => 'Hero Subtitle',
                'name'         => 'fw_page_hero_subtitle',
                'type'         => 'textarea',
                'instructions' => 'Short paragraph below the headline. 1–2 sentences.',
                'rows'         => 2,
                'new_lines'    => '',
                'required'     => 0,
            ],
            [
                'key'          => 'field_fw_page_hero_bg',
                'label'        => 'Background Image',
                'name'         => 'fw_page_hero_bg',
                'type'         => 'image',
                'instructions' => 'Optional full-width banner image (1600×600 px recommended).',
                'return_format'=> 'url',
                'library'      => 'all',
                'required'     => 0,
            ],
        ],
        'location' => [
            [ [ 'param' => 'page_template', 'operator' => '==', 'value' => 'page-templates/template-take-action.php' ] ],
            [ [ 'param' => 'page_template', 'operator' => '==', 'value' => 'page-templates/template-spiritual-formation.php' ] ],
            [ [ 'param' => 'page_template', 'operator' => '==', 'value' => 'page-templates/template-know-your-rights.php' ] ],
            [ [ 'param' => 'page_template', 'operator' => '==', 'value' => 'page-templates/template-network.php' ] ],
            [ [ 'param' => 'page_template', 'operator' => '==', 'value' => 'page-templates/template-stories.php' ] ],
            [ [ 'param' => 'page_template', 'operator' => '==', 'value' => 'page-templates/template-news.php' ] ],
            [ [ 'param' => 'page_template', 'operator' => '==', 'value' => 'page-templates/template-map.php' ] ],
            [ [ 'param' => 'page_template', 'operator' => '==', 'value' => 'page-templates/template-find-support.php' ] ],
            [ [ 'param' => 'page_template', 'operator' => '==', 'value' => 'page-templates/template-about.php' ] ],
        ],
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'field',
    ] );
}

// ============================================================
// TAKE ACTION PAGE — action card content
// ============================================================
function fw_acf_group_page_take_action() {
    acf_add_local_field_group( [
        'key'    => 'group_fw_take_action',
        'title'  => 'Take Action — Audience Cards',
        'fields' => [

            // Card 1
            [
                'key'          => 'field_fw_ta_card1_audience',
                'label'        => 'Card 1 — Audience Label',
                'name'         => 'fw_ta_card1_audience',
                'type'         => 'text',
                'default_value'=> "I'm uncertain",
                'wrapper'      => [ 'width' => '50' ],
            ],
            [
                'key'          => 'field_fw_ta_card1_title',
                'label'        => 'Card 1 — Title',
                'name'         => 'fw_ta_card1_title',
                'type'         => 'text',
                'default_value'=> 'Start by learning',
                'wrapper'      => [ 'width' => '50' ],
            ],
            [
                'key'          => 'field_fw_ta_card1_desc',
                'label'        => 'Card 1 — Description',
                'name'         => 'fw_ta_card1_desc',
                'type'         => 'textarea',
                'rows'         => 3,
                'new_lines'    => '',
                'default_value'=> "You sense something is wrong but aren't sure what faithful engagement looks like. Start with our resources — guides, articles, and tools to help you understand immigration through a Gospel lens.",
            ],
            [
                'key'          => 'field_fw_ta_card1_btn_label',
                'label'        => 'Card 1 — Button Label',
                'name'         => 'fw_ta_card1_btn_label',
                'type'         => 'text',
                'default_value'=> 'Browse Resources',
                'wrapper'      => [ 'width' => '50' ],
            ],
            [
                'key'          => 'field_fw_ta_card1_btn_url',
                'label'        => 'Card 1 — Button URL',
                'name'         => 'fw_ta_card1_btn_url',
                'type'         => 'url',
                'default_value'=> '/resources',
                'wrapper'      => [ 'width' => '50' ],
            ],

            // Card 2
            [
                'key'          => 'field_fw_ta_card2_audience',
                'label'        => 'Card 2 — Audience Label',
                'name'         => 'fw_ta_card2_audience',
                'type'         => 'text',
                'default_value'=> "I'm ready to organize",
                'wrapper'      => [ 'width' => '50' ],
            ],
            [
                'key'          => 'field_fw_ta_card2_title',
                'label'        => 'Card 2 — Title',
                'name'         => 'fw_ta_card2_title',
                'type'         => 'text',
                'default_value'=> 'Find your local group',
                'wrapper'      => [ 'width' => '50' ],
            ],
            [
                'key'          => 'field_fw_ta_card2_desc',
                'label'        => 'Card 2 — Description',
                'name'         => 'fw_ta_card2_desc',
                'type'         => 'textarea',
                'rows'         => 3,
                'new_lines'    => '',
                'default_value'=> "You're a church leader, pastor, or congregation ready to act. Connect with other faithful witnesses in your area, access organizing toolkits, and join the national network.",
            ],
            [
                'key'          => 'field_fw_ta_card2_btn_label',
                'label'        => 'Card 2 — Button Label',
                'name'         => 'fw_ta_card2_btn_label',
                'type'         => 'text',
                'default_value'=> 'Find a Group Near Me',
                'wrapper'      => [ 'width' => '50' ],
            ],
            [
                'key'          => 'field_fw_ta_card2_btn_url',
                'label'        => 'Card 2 — Button URL',
                'name'         => 'fw_ta_card2_btn_url',
                'type'         => 'url',
                'default_value'=> '/network',
                'wrapper'      => [ 'width' => '50' ],
            ],

            // Card 3
            [
                'key'          => 'field_fw_ta_card3_audience',
                'label'        => 'Card 3 — Audience Label',
                'name'         => 'fw_ta_card3_audience',
                'type'         => 'text',
                'default_value'=> "I'm directly affected",
                'wrapper'      => [ 'width' => '50' ],
            ],
            [
                'key'          => 'field_fw_ta_card3_title',
                'label'        => 'Card 3 — Title',
                'name'         => 'fw_ta_card3_title',
                'type'         => 'text',
                'default_value'=> 'Connect with support',
                'wrapper'      => [ 'width' => '50' ],
            ],
            [
                'key'          => 'field_fw_ta_card3_desc',
                'label'        => 'Card 3 — Description',
                'name'         => 'fw_ta_card3_desc',
                'type'         => 'textarea',
                'rows'         => 3,
                'new_lines'    => '',
                'default_value'=> 'You or someone you love is navigating the immigration system right now. Access practical Know Your Rights information, find a local group, and connect with a community that will stand with you.',
            ],
            [
                'key'          => 'field_fw_ta_card3_btn_label',
                'label'        => 'Card 3 — Button Label',
                'name'         => 'fw_ta_card3_btn_label',
                'type'         => 'text',
                'default_value'=> 'Know Your Rights',
                'wrapper'      => [ 'width' => '50' ],
            ],
            [
                'key'          => 'field_fw_ta_card3_btn_url',
                'label'        => 'Card 3 — Button URL',
                'name'         => 'fw_ta_card3_btn_url',
                'type'         => 'url',
                'default_value'=> '/know-your-rights',
                'wrapper'      => [ 'width' => '50' ],
            ],

        ],
        'location' => [
            [ [ 'param' => 'page_template', 'operator' => '==', 'value' => 'page-templates/template-take-action.php' ] ],
        ],
        'menu_order'            => 5,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'field',
    ] );
}

// ============================================================
// SPIRITUAL FORMATION PAGE — intro + pathway cards
// ============================================================
function fw_acf_group_page_formation() {
    acf_add_local_field_group( [
        'key'    => 'group_fw_formation',
        'title'  => 'Spiritual Formation — Page Content',
        'fields' => [

            [
                'key'          => 'field_fw_formation_intro',
                'label'        => 'Intro Paragraph',
                'name'         => 'fw_formation_intro',
                'type'         => 'textarea',
                'instructions' => 'The opening paragraph beneath the hero. 2–4 sentences.',
                'rows'         => 4,
                'new_lines'    => '',
                'default_value'=> 'The Faithful Witness Campaign integrates spiritual formation directly into local organizing work. We believe that sustainable advocacy flows from a rooted spiritual life — not from political urgency alone. Formation before and beneath action is not a slogan. It is how we sustain ourselves for the long road ahead.',
            ],

            // Pathway 1
            [
                'key'          => 'field_fw_formation_path1_title',
                'label'        => 'Pathway 1 — Title',
                'name'         => 'fw_formation_path1_title',
                'type'         => 'text',
                'default_value'=> 'Prayer & Lament',
                'wrapper'      => [ 'width' => '50' ],
            ],
            [
                'key'          => 'field_fw_formation_path1_desc',
                'label'        => 'Pathway 1 — Description',
                'name'         => 'fw_formation_path1_desc',
                'type'         => 'textarea',
                'rows'         => 3,
                'new_lines'    => '',
                'default_value'=> "Prayers, liturgies, and lament practices for congregations standing at the intersection of faith and injustice. You don't have to be okay. You just have to keep praying.",
                'wrapper'      => [ 'width' => '50' ],
            ],

            // Pathway 2
            [
                'key'          => 'field_fw_formation_path2_title',
                'label'        => 'Pathway 2 — Title',
                'name'         => 'fw_formation_path2_title',
                'type'         => 'text',
                'default_value'=> 'Scripture & Discernment',
                'wrapper'      => [ 'width' => '50' ],
            ],
            [
                'key'          => 'field_fw_formation_path2_desc',
                'label'        => 'Pathway 2 — Description',
                'name'         => 'fw_formation_path2_desc',
                'type'         => 'textarea',
                'rows'         => 3,
                'new_lines'    => '',
                'default_value'=> 'Bible study guides, sermon resources, and discernment frameworks for congregations wrestling with immigration through a Gospel lens. What does the text say? What does it ask of us?',
                'wrapper'      => [ 'width' => '50' ],
            ],

            // Pathway 3
            [
                'key'          => 'field_fw_formation_path3_title',
                'label'        => 'Pathway 3 — Title',
                'name'         => 'fw_formation_path3_title',
                'type'         => 'text',
                'default_value'=> 'Pastoral Care Resources',
                'wrapper'      => [ 'width' => '50' ],
            ],
            [
                'key'          => 'field_fw_formation_path3_desc',
                'label'        => 'Pathway 3 — Description',
                'name'         => 'fw_formation_path3_desc',
                'type'         => 'textarea',
                'rows'         => 3,
                'new_lines'    => '',
                'default_value'=> 'Tools for pastors and church leaders caring for immigrant congregants, processing vicarious trauma, and sustaining themselves and their teams for the long work of justice.',
                'wrapper'      => [ 'width' => '50' ],
            ],

            // Scripture pullquote
            [
                'key'          => 'field_fw_formation_scripture_text',
                'label'        => 'Scripture Pullquote',
                'name'         => 'fw_formation_scripture_text',
                'type'         => 'textarea',
                'instructions' => 'Bible verse displayed at the bottom of the page.',
                'rows'         => 2,
                'new_lines'    => '',
                'default_value'=> 'We cannot help speaking about what we have seen and heard.',
                'wrapper'      => [ 'width' => '75' ],
            ],
            [
                'key'          => 'field_fw_formation_scripture_ref',
                'label'        => 'Scripture Reference',
                'name'         => 'fw_formation_scripture_ref',
                'type'         => 'text',
                'default_value'=> 'Acts 4:20',
                'placeholder'  => 'e.g. Acts 4:20',
                'wrapper'      => [ 'width' => '25' ],
            ],

        ],
        'location' => [
            [ [ 'param' => 'page_template', 'operator' => '==', 'value' => 'page-templates/template-spiritual-formation.php' ] ],
        ],
        'menu_order'            => 5,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'field',
    ] );
}

// ============================================================
// KNOW YOUR RIGHTS PAGE — section content + download URL
// ============================================================
function fw_acf_group_page_kyr() {
    acf_add_local_field_group( [
        'key'    => 'group_fw_kyr',
        'title'  => 'Know Your Rights — Page Content',
        'fields' => [

            [
                'key'          => 'field_fw_kyr_download_url',
                'label'        => '"Download All Materials" URL',
                'name'         => 'fw_kyr_download_all_url',
                'type'         => 'url',
                'instructions' => 'Link to the ZIP file or Google Drive folder with all KYR materials.',
                'required'     => 0,
            ],

            [
                'key'          => 'field_fw_kyr_ice_content',
                'label'        => 'Section 1 — If ICE Comes to Your Door',
                'name'         => 'fw_kyr_ice_content',
                'type'         => 'wysiwyg',
                'instructions' => 'Bullet points and paragraphs for the "If ICE comes to your door" section. Use the toolbar to add bullet lists.',
                'tabs'         => 'visual',
                'toolbar'      => 'basic',
                'media_upload' => 0,
                'required'     => 0,
            ],

            [
                'key'          => 'field_fw_kyr_detained_content',
                'label'        => 'Section 2 — If Someone Is Detained',
                'name'         => 'fw_kyr_detained_content',
                'type'         => 'wysiwyg',
                'instructions' => 'Bullet points and paragraphs for the "If someone is detained" section.',
                'tabs'         => 'visual',
                'toolbar'      => 'basic',
                'media_upload' => 0,
                'required'     => 0,
            ],

            [
                'key'          => 'field_fw_kyr_sanctuary_content',
                'label'        => 'Section 3 — For Congregations & Sanctuaries',
                'name'         => 'fw_kyr_sanctuary_content',
                'type'         => 'wysiwyg',
                'instructions' => 'Bullet points and paragraphs for the congregation sanctuary section.',
                'tabs'         => 'visual',
                'toolbar'      => 'basic',
                'media_upload' => 0,
                'required'     => 0,
            ],

        ],
        'location' => [
            [ [ 'param' => 'page_template', 'operator' => '==', 'value' => 'page-templates/template-know-your-rights.php' ] ],
        ],
        'menu_order'            => 5,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'field',
    ] );
}

// ============================================================
// ACF OPTIONS PAGE — Homepage Settings
// ============================================================
function fw_acf_options_homepage() {
    if ( ! function_exists( 'acf_add_options_page' ) ) return;

    acf_add_options_sub_page( [
        'page_title'  => 'Homepage Settings',
        'menu_title'  => 'Homepage Settings',
        'parent_slug' => 'faithfulwitness-hub',
        'capability'  => 'edit_posts',
        'redirect'    => false,
    ] );

    acf_add_local_field_group( [
        'key'    => 'group_fw_homepage_options',
        'title'  => 'Homepage Settings',
        'fields' => [

            // ── HERO TAB ─────────────────────────────────────────
            [
                'key'   => 'field_fw_hp_tab_hero',
                'label' => 'Hero Banner',
                'type'  => 'tab',
            ],
            [
                'key'           => 'field_fw_hero_eyebrow',
                'label'         => 'Eyebrow Text',
                'name'          => 'fw_hero_eyebrow',
                'type'          => 'text',
                'instructions'  => 'Small label above the main headline. Keep it under 6 words.',
                'default_value' => 'A Gospel-Centered Campaign',
                'placeholder'   => 'e.g. A Gospel-Centered Campaign',
            ],
            [
                'key'           => 'field_fw_hero_title',
                'label'         => 'Main Headline',
                'name'          => 'fw_hero_title',
                'type'          => 'text',
                'instructions'  => 'The large H1 in the hero banner. Keep it under 10 words.',
                'default_value' => 'A Gospel-Centered Response for a Divided Time',
            ],
            [
                'key'           => 'field_fw_hero_subtitle',
                'label'         => 'Subtitle',
                'name'          => 'fw_hero_subtitle',
                'type'          => 'textarea',
                'instructions'  => 'Paragraph below the headline. 1–2 sentences.',
                'rows'          => 2,
                'new_lines'     => '',
                'default_value' => 'Forming the Church for courageous, nonviolent, Gospel-rooted engagement around immigration.',
            ],
            [
                'key'           => 'field_fw_hero_bg',
                'label'         => 'Background Image',
                'name'          => 'fw_hero_bg',
                'type'          => 'image',
                'instructions'  => 'Wide banner image (1600×600 px recommended). Leave blank to use the default.',
                'return_format' => 'url',
                'library'       => 'all',
            ],
            [
                'key'           => 'field_fw_hero_cta1_label',
                'label'         => 'Button 1 — Label',
                'name'          => 'fw_hero_cta1_label',
                'type'          => 'text',
                'default_value' => 'Join the Campaign',
                'wrapper'       => [ 'width' => '50' ],
            ],
            [
                'key'           => 'field_fw_hero_cta1_url',
                'label'         => 'Button 1 — URL',
                'name'          => 'fw_hero_cta1_url',
                'type'          => 'url',
                'instructions'  => 'Where the primary (accent) button links.',
                'wrapper'       => [ 'width' => '50' ],
            ],
            [
                'key'           => 'field_fw_hero_cta2_label',
                'label'         => 'Button 2 — Label',
                'name'          => 'fw_hero_cta2_label',
                'type'          => 'text',
                'default_value' => 'Find Your Network',
                'wrapper'       => [ 'width' => '50' ],
            ],
            [
                'key'           => 'field_fw_hero_cta2_url',
                'label'         => 'Button 2 — URL',
                'name'          => 'fw_hero_cta2_url',
                'type'          => 'url',
                'instructions'  => 'Where the secondary (outline) button links.',
                'wrapper'       => [ 'width' => '50' ],
            ],

            // ── VALUES STRIP TAB ─────────────────────────────────
            [
                'key'   => 'field_fw_hp_tab_values',
                'label' => 'Values Strip',
                'type'  => 'tab',
            ],
            [
                'key'     => 'field_fw_hp_values_note',
                'label'   => '',
                'name'    => '',
                'type'    => 'message',
                'message' => 'The "We Choose" strip shows four value pairs (e.g. "Hope over despair"). Edit each word and contrast phrase below.',
            ],
            [
                'key'           => 'field_fw_value1_word',
                'label'         => 'Value 1 — Word',
                'name'          => 'fw_value1_word',
                'type'          => 'text',
                'default_value' => 'Hope',
                'wrapper'       => [ 'width' => '50' ],
            ],
            [
                'key'           => 'field_fw_value1_over',
                'label'         => 'Value 1 — "over ___"',
                'name'          => 'fw_value1_over',
                'type'          => 'text',
                'default_value' => 'over despair',
                'wrapper'       => [ 'width' => '50' ],
            ],
            [
                'key'           => 'field_fw_value2_word',
                'label'         => 'Value 2 — Word',
                'name'          => 'fw_value2_word',
                'type'          => 'text',
                'default_value' => 'Courage',
                'wrapper'       => [ 'width' => '50' ],
            ],
            [
                'key'           => 'field_fw_value2_over',
                'label'         => 'Value 2 — "over ___"',
                'name'          => 'fw_value2_over',
                'type'          => 'text',
                'default_value' => 'over silence',
                'wrapper'       => [ 'width' => '50' ],
            ],
            [
                'key'           => 'field_fw_value3_word',
                'label'         => 'Value 3 — Word',
                'name'          => 'fw_value3_word',
                'type'          => 'text',
                'default_value' => 'Nonviolence',
                'wrapper'       => [ 'width' => '50' ],
            ],
            [
                'key'           => 'field_fw_value3_over',
                'label'         => 'Value 3 — "over ___"',
                'name'          => 'fw_value3_over',
                'type'          => 'text',
                'default_value' => 'over fear',
                'wrapper'       => [ 'width' => '50' ],
            ],
            [
                'key'           => 'field_fw_value4_word',
                'label'         => 'Value 4 — Word',
                'name'          => 'fw_value4_word',
                'type'          => 'text',
                'default_value' => 'Love',
                'wrapper'       => [ 'width' => '50' ],
            ],
            [
                'key'           => 'field_fw_value4_over',
                'label'         => 'Value 4 — "over ___"',
                'name'          => 'fw_value4_over',
                'type'          => 'text',
                'default_value' => 'over division',
                'wrapper'       => [ 'width' => '50' ],
            ],

            // ── THREE COMMITMENTS TAB ────────────────────────────
            [
                'key'   => 'field_fw_hp_tab_commitments',
                'label' => 'Three Commitments',
                'type'  => 'tab',
            ],
            [
                'key'           => 'field_fw_commit1_title',
                'label'         => 'Commitment 1 — Title',
                'name'          => 'fw_commit1_title',
                'type'          => 'text',
                'default_value' => 'Local Grassroots Movements & Formation',
            ],
            [
                'key'           => 'field_fw_commit1_desc',
                'label'         => 'Commitment 1 — Description',
                'name'          => 'fw_commit1_desc',
                'type'          => 'textarea',
                'rows'          => 3,
                'new_lines'     => '',
                'default_value' => 'Cultivating faithful leadership in local communities — rooting people in Gospel values before, during, and after action.',
            ],
            [
                'key'           => 'field_fw_commit1_url',
                'label'         => 'Commitment 1 — Learn More URL',
                'name'          => 'fw_commit1_url',
                'type'          => 'url',
                'instructions'  => 'Where the "Learn more →" link points.',
                'default_value' => '/spiritual-formation',
            ],
            [
                'key'           => 'field_fw_commit2_title',
                'label'         => 'Commitment 2 — Title',
                'name'          => 'fw_commit2_title',
                'type'          => 'text',
                'default_value' => 'Presence & Accompaniment',
            ],
            [
                'key'           => 'field_fw_commit2_desc',
                'label'         => 'Commitment 2 — Description',
                'name'          => 'fw_commit2_desc',
                'type'          => 'textarea',
                'rows'          => 3,
                'new_lines'     => '',
                'default_value' => 'Walking with those navigating fear and uncertainty — court accompaniment, Know Your Rights trainings, food and transportation assistance, and pastoral care.',
            ],
            [
                'key'           => 'field_fw_commit2_url',
                'label'         => 'Commitment 2 — Learn More URL',
                'name'          => 'fw_commit2_url',
                'type'          => 'url',
                'default_value' => '/know-your-rights',
            ],
            [
                'key'           => 'field_fw_commit3_title',
                'label'         => 'Commitment 3 — Title',
                'name'          => 'fw_commit3_title',
                'type'          => 'text',
                'default_value' => 'Public Witness in the Public Square',
            ],
            [
                'key'           => 'field_fw_commit3_desc',
                'label'         => 'Commitment 3 — Description',
                'name'          => 'fw_commit3_desc',
                'type'          => 'textarea',
                'rows'          => 3,
                'new_lines'     => '',
                'default_value' => 'Speaking with one moral voice on policy that upholds human dignity, due process, humanitarian protections, and nonviolence.',
            ],
            [
                'key'           => 'field_fw_commit3_url',
                'label'         => 'Commitment 3 — Learn More URL',
                'name'          => 'fw_commit3_url',
                'type'          => 'url',
                'default_value' => '/take-action',
            ],

            // ── AUDIENCE CARDS TAB ───────────────────────────────
            [
                'key'   => 'field_fw_hp_tab_audience',
                'label' => 'Audience Cards',
                'type'  => 'tab',
            ],
            // Card 1
            [
                'key'           => 'field_fw_audience1_label',
                'label'         => 'Card 1 — Eyebrow Label',
                'name'          => 'fw_audience1_label',
                'type'          => 'text',
                'default_value' => 'Starting Point',
                'wrapper'       => [ 'width' => '50' ],
            ],
            [
                'key'           => 'field_fw_audience1_title',
                'label'         => 'Card 1 — Title',
                'name'          => 'fw_audience1_title',
                'type'          => 'text',
                'default_value' => 'For those who are uncertain',
                'wrapper'       => [ 'width' => '50' ],
            ],
            [
                'key'           => 'field_fw_audience1_desc',
                'label'         => 'Card 1 — Description',
                'name'          => 'fw_audience1_desc',
                'type'          => 'textarea',
                'rows'          => 3,
                'new_lines'     => '',
                'default_value' => "You sense something is wrong but aren't sure what faithful engagement looks like. You want to understand the issues through a Gospel lens before acting. This is a safe place to learn, ask hard questions, and be formed.",
            ],
            [
                'key'           => 'field_fw_audience1_btn_label',
                'label'         => 'Card 1 — Button Label',
                'name'          => 'fw_audience1_btn_label',
                'type'          => 'text',
                'default_value' => 'Start by learning',
                'wrapper'       => [ 'width' => '50' ],
            ],
            [
                'key'           => 'field_fw_audience1_btn_url',
                'label'         => 'Card 1 — Button URL',
                'name'          => 'fw_audience1_btn_url',
                'type'          => 'url',
                'default_value' => '/resources',
                'wrapper'       => [ 'width' => '50' ],
            ],
            // Card 2
            [
                'key'           => 'field_fw_audience2_label',
                'label'         => 'Card 2 — Eyebrow Label',
                'name'          => 'fw_audience2_label',
                'type'          => 'text',
                'default_value' => 'Ready to Organize',
                'wrapper'       => [ 'width' => '50' ],
            ],
            [
                'key'           => 'field_fw_audience2_title',
                'label'         => 'Card 2 — Title',
                'name'          => 'fw_audience2_title',
                'type'          => 'text',
                'default_value' => 'For those ready to engage',
                'wrapper'       => [ 'width' => '50' ],
            ],
            [
                'key'           => 'field_fw_audience2_desc',
                'label'         => 'Card 2 — Description',
                'name'          => 'fw_audience2_desc',
                'type'          => 'textarea',
                'rows'          => 3,
                'new_lines'     => '',
                'default_value' => "You're a church leader, pastor, or congregation ready to move from concern to action. You want practical tools, community support, and a network of faithful witnesses who will walk alongside you.",
            ],
            [
                'key'           => 'field_fw_audience2_btn_label',
                'label'         => 'Card 2 — Button Label',
                'name'          => 'fw_audience2_btn_label',
                'type'          => 'text',
                'default_value' => 'Find your local group',
                'wrapper'       => [ 'width' => '50' ],
            ],
            [
                'key'           => 'field_fw_audience2_btn_url',
                'label'         => 'Card 2 — Button URL',
                'name'          => 'fw_audience2_btn_url',
                'type'          => 'url',
                'default_value' => '/network',
                'wrapper'       => [ 'width' => '50' ],
            ],
            // Card 3
            [
                'key'           => 'field_fw_audience3_label',
                'label'         => 'Card 3 — Eyebrow Label',
                'name'          => 'fw_audience3_label',
                'type'          => 'text',
                'default_value' => 'Direct Support',
                'wrapper'       => [ 'width' => '50' ],
            ],
            [
                'key'           => 'field_fw_audience3_title',
                'label'         => 'Card 3 — Title',
                'name'          => 'fw_audience3_title',
                'type'          => 'text',
                'default_value' => 'For those directly affected',
                'wrapper'       => [ 'width' => '50' ],
            ],
            [
                'key'           => 'field_fw_audience3_desc',
                'label'         => 'Card 3 — Description',
                'name'          => 'fw_audience3_desc',
                'type'          => 'textarea',
                'rows'          => 3,
                'new_lines'     => '',
                'default_value' => "You or someone you love is navigating the immigration system right now. You need practical help, legal information, and a community that will stand with you without judgment or fear.",
            ],
            [
                'key'           => 'field_fw_audience3_btn_label',
                'label'         => 'Card 3 — Button Label',
                'name'          => 'fw_audience3_btn_label',
                'type'          => 'text',
                'default_value' => 'Connect with support',
                'wrapper'       => [ 'width' => '50' ],
            ],
            [
                'key'           => 'field_fw_audience3_btn_url',
                'label'         => 'Card 3 — Button URL',
                'name'          => 'fw_audience3_btn_url',
                'type'          => 'url',
                'default_value' => '/know-your-rights',
                'wrapper'       => [ 'width' => '50' ],
            ],

            // ── SCRIPTURE ANCHOR TAB ─────────────────────────────
            [
                'key'   => 'field_fw_hp_tab_scripture',
                'label' => 'Scripture Anchor',
                'type'  => 'tab',
            ],
            [
                'key'           => 'field_fw_scripture_text',
                'label'         => 'Scripture Text',
                'name'          => 'fw_scripture_text',
                'type'          => 'textarea',
                'instructions'  => 'Bible verse displayed in the full-width scripture section.',
                'rows'          => 2,
                'new_lines'     => '',
                'default_value' => 'As for us, we cannot help speaking about what we have seen and heard.',
                'wrapper'       => [ 'width' => '75' ],
            ],
            [
                'key'           => 'field_fw_scripture_ref',
                'label'         => 'Scripture Reference',
                'name'          => 'fw_scripture_ref',
                'type'          => 'text',
                'default_value' => 'Acts 4:20',
                'placeholder'   => 'e.g. Acts 4:20',
                'wrapper'       => [ 'width' => '25' ],
            ],

            // ── CAMPAIGN SECTION TAB ─────────────────────────────
            [
                'key'   => 'field_fw_hp_tab_campaign',
                'label' => 'Campaign Highlight',
                'type'  => 'tab',
            ],
            [
                'key'           => 'field_fw_campaign_headline',
                'label'         => 'Campaign Headline',
                'name'          => 'fw_campaign_headline',
                'type'          => 'text',
                'instructions'  => 'Shown when no Initiative post is published. Keep it under 8 words.',
                'default_value' => 'Stand With Immigrant Families',
                'placeholder'   => 'e.g. Stand With Immigrant Families',
            ],
            [
                'key'           => 'field_fw_campaign_description',
                'label'         => 'Campaign Description',
                'name'          => 'fw_campaign_description',
                'type'          => 'textarea',
                'instructions'  => 'Shown when no Initiative post is published. 1–2 sentences.',
                'rows'          => 3,
                'new_lines'     => '',
                'default_value' => 'The moment calls for faithful witnesses to speak and act with courage. Join churches across the country in this critical campaign.',
            ],
            [
                'key'           => 'field_fw_campaign_cta_label',
                'label'         => 'Button Label',
                'name'          => 'fw_campaign_cta_label',
                'type'          => 'text',
                'instructions'  => 'Text on the action button.',
                'default_value' => 'Take Action',
                'wrapper'       => [ 'width' => '50' ],
            ],
            [
                'key'           => 'field_fw_campaign_cta_url',
                'label'         => 'Button URL',
                'name'          => 'fw_campaign_cta_url',
                'type'          => 'url',
                'instructions'  => 'Where the action button links to.',
                'wrapper'       => [ 'width' => '50' ],
            ],

            // ── PARTNER LOGOS TAB ────────────────────────────────
            [
                'key'   => 'field_fw_hp_tab_partners',
                'label' => 'Partner Logos',
                'type'  => 'tab',
            ],
            [
                'key'          => 'field_fw_partner1_name',
                'label'        => 'Partner 1 — Name',
                'name'         => 'fw_partner1_name',
                'type'         => 'text',
                'default_value'=> 'NaLEC',
                'wrapper'      => [ 'width' => '33' ],
            ],
            [
                'key'          => 'field_fw_partner1_logo',
                'label'        => 'Partner 1 — Logo',
                'name'         => 'fw_partner1_logo_url',
                'type'         => 'image',
                'return_format'=> 'url',
                'instructions' => 'PNG preferred. Displayed at ~80px tall.',
                'wrapper'      => [ 'width' => '33' ],
            ],
            [
                'key'          => 'field_fw_partner1_url',
                'label'        => 'Partner 1 — Website',
                'name'         => 'fw_partner1_url',
                'type'         => 'url',
                'default_value'=> 'https://nalec.org',
                'wrapper'      => [ 'width' => '33' ],
            ],
            [
                'key'          => 'field_fw_partner2_name',
                'label'        => 'Partner 2 — Name',
                'name'         => 'fw_partner2_name',
                'type'         => 'text',
                'default_value'=> 'CCDA',
                'wrapper'      => [ 'width' => '33' ],
            ],
            [
                'key'          => 'field_fw_partner2_logo',
                'label'        => 'Partner 2 — Logo',
                'name'         => 'fw_partner2_logo_url',
                'type'         => 'image',
                'return_format'=> 'url',
                'wrapper'      => [ 'width' => '33' ],
            ],
            [
                'key'          => 'field_fw_partner2_url',
                'label'        => 'Partner 2 — Website',
                'name'         => 'fw_partner2_url',
                'type'         => 'url',
                'default_value'=> 'https://ccda.org',
                'wrapper'      => [ 'width' => '33' ],
            ],
            [
                'key'          => 'field_fw_partner3_name',
                'label'        => 'Partner 3 — Name',
                'name'         => 'fw_partner3_name',
                'type'         => 'text',
                'default_value'=> 'World Relief',
                'wrapper'      => [ 'width' => '33' ],
            ],
            [
                'key'          => 'field_fw_partner3_logo',
                'label'        => 'Partner 3 — Logo',
                'name'         => 'fw_partner3_logo_url',
                'type'         => 'image',
                'return_format'=> 'url',
                'wrapper'      => [ 'width' => '33' ],
            ],
            [
                'key'          => 'field_fw_partner3_url',
                'label'        => 'Partner 3 — Website',
                'name'         => 'fw_partner3_url',
                'type'         => 'url',
                'default_value'=> 'https://worldrelief.org',
                'wrapper'      => [ 'width' => '33' ],
            ],
            [
                'key'          => 'field_fw_partner4_name',
                'label'        => 'Partner 4 — Name',
                'name'         => 'fw_partner4_name',
                'type'         => 'text',
                'default_value'=> 'Undivided',
                'wrapper'      => [ 'width' => '33' ],
            ],
            [
                'key'          => 'field_fw_partner4_logo',
                'label'        => 'Partner 4 — Logo',
                'name'         => 'fw_partner4_logo_url',
                'type'         => 'image',
                'return_format'=> 'url',
                'wrapper'      => [ 'width' => '33' ],
            ],
            [
                'key'          => 'field_fw_partner4_url',
                'label'        => 'Partner 4 — Website',
                'name'         => 'fw_partner4_url',
                'type'         => 'url',
                'default_value'=> 'https://undivided.us',
                'wrapper'      => [ 'width' => '33' ],
            ],

        ],
        'location' => [
            [ [ 'param' => 'options_page', 'operator' => '==', 'value' => 'acf-options-homepage-settings' ] ],
        ],
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'top',
        'instruction_placement' => 'field',
    ] );
}

// ============================================================
// ACF NOTICE — prompt install if not present
// ============================================================
add_action( 'admin_notices', 'fw_acf_install_notice' );
function fw_acf_install_notice() {
    if ( function_exists( 'acf_add_local_field_group' ) ) return;
    if ( ! current_user_can( 'install_plugins' ) ) return;
    if ( get_option( 'fw_acf_notice_dismissed' ) ) return;

    $install_url = admin_url( 'plugin-install.php?s=advanced+custom+fields&tab=search&type=term' );
    ?>
    <div class="notice notice-info is-dismissible" id="fw-acf-notice">
        <p>
            <strong>Faithful Witness:</strong>
            For the best content editing experience, please
            <a href="<?php echo esc_url( $install_url ); ?>"><strong>install Advanced Custom Fields (free)</strong></a>.
            It adds clean, guided forms for adding resources, events, media hits, and partners.
            The site works without it, but the editing forms are much simpler with it.
        </p>
    </div>
    <script>
    document.addEventListener('DOMContentLoaded', function() {
        var n = document.getElementById('fw-acf-notice');
        if (!n) return;
        n.querySelector('.notice-dismiss') && n.querySelector('.notice-dismiss').addEventListener('click', function() {
            fetch('<?php echo esc_url( admin_url( 'admin-ajax.php' ) ); ?>', {
                method: 'POST',
                body: new URLSearchParams({ action: 'fw_dismiss_acf_notice', nonce: '<?php echo esc_js( wp_create_nonce( 'fw_dismiss_acf' ) ); ?>' }),
            });
        });
    });
    </script>
    <?php
}

add_action( 'wp_ajax_fw_dismiss_acf_notice', function () {
    check_ajax_referer( 'fw_dismiss_acf', 'nonce' );
    update_option( 'fw_acf_notice_dismissed', 1 );
    wp_send_json_success();
} );

// ============================================================
// ABOUT PAGE — template-about.php
// ============================================================
function fw_acf_group_page_about() {
    acf_add_local_field_group( [
        'key'    => 'group_fw_page_about',
        'title'  => __( 'About — Page Content', 'faithfulwitness' ),
        'fields' => [
            [
                'key'          => 'field_fw_about_vision',
                'label'        => __( 'Vision Statement', 'faithfulwitness' ),
                'name'         => 'fw_about_vision',
                'type'         => 'textarea',
                'instructions' => __( 'One paragraph describing the long-term vision of Faithful Witness.', 'faithfulwitness' ),
                'rows'         => 4,
            ],
            [
                'key'          => 'field_fw_about_mission',
                'label'        => __( 'Mission Statement', 'faithfulwitness' ),
                'name'         => 'fw_about_mission',
                'type'         => 'textarea',
                'instructions' => __( 'One paragraph describing what Faithful Witness does and for whom.', 'faithfulwitness' ),
                'rows'         => 4,
            ],
            [
                'key'          => 'field_fw_about_distinctives',
                'label'        => __( 'Our Distinctives', 'faithfulwitness' ),
                'name'         => 'fw_about_distinctives',
                'type'         => 'wysiwyg',
                'instructions' => __( 'What makes Faithful Witness different? Use bullet points or short paragraphs.', 'faithfulwitness' ),
                'tabs'         => 'all',
                'toolbar'      => 'basic',
                'media_upload' => 0,
            ],
            [
                'key'          => 'field_fw_about_national_policies',
                'label'        => __( 'National Policy Positions', 'faithfulwitness' ),
                'name'         => 'fw_about_national_policies',
                'type'         => 'wysiwyg',
                'instructions' => __( 'Faithful Witness positions on federal immigration policy.', 'faithfulwitness' ),
                'tabs'         => 'all',
                'toolbar'      => 'basic',
                'media_upload' => 0,
            ],
            [
                'key'          => 'field_fw_about_local_policies',
                'label'        => __( 'Local Policy Positions', 'faithfulwitness' ),
                'name'         => 'fw_about_local_policies',
                'type'         => 'wysiwyg',
                'instructions' => __( 'Positions on state and local immigration enforcement and sanctuary policies.', 'faithfulwitness' ),
                'tabs'         => 'all',
                'toolbar'      => 'basic',
                'media_upload' => 0,
            ],
            [
                'key'          => 'field_fw_about_scripture_text',
                'label'        => __( 'Scripture Pullquote', 'faithfulwitness' ),
                'name'         => 'fw_about_scripture_text',
                'type'         => 'textarea',
                'instructions' => __( 'A scripture verse displayed prominently on the About page.', 'faithfulwitness' ),
                'rows'         => 3,
            ],
            [
                'key'          => 'field_fw_about_scripture_ref',
                'label'        => __( 'Scripture Reference', 'faithfulwitness' ),
                'name'         => 'fw_about_scripture_ref',
                'type'         => 'text',
                'instructions' => __( 'E.g. "Leviticus 19:33–34"', 'faithfulwitness' ),
            ],
        ],
        'location' => [
            [ [ 'param' => 'page_template', 'operator' => '==', 'value' => 'page-templates/template-about.php' ] ],
        ],
        'menu_order' => 5,
        'style'      => 'default',
    ] );
}

// ============================================================
// SUPPORT ENTRIES — fw_support_entry
// ============================================================
function fw_acf_group_support_entries() {
    acf_add_local_field_group( [
        'key'    => 'group_fw_support_entry',
        'title'  => __( 'Support Entry Details', 'faithfulwitness' ),
        'fields' => [
            [
                'key'           => 'field_fw_support_type',
                'label'         => __( 'Support Type', 'faithfulwitness' ),
                'name'          => 'fw_support_type',
                'type'          => 'select',
                'instructions'  => __( 'Choose the category that best describes this organization\'s services.', 'faithfulwitness' ),
                'choices'       => [
                    'basic_needs' => __( 'Basic Needs (food, housing, clothing)', 'faithfulwitness' ),
                    'legal'       => __( 'Legal Services', 'faithfulwitness' ),
                    'spiritual'   => __( 'Spiritual & Pastoral Support', 'faithfulwitness' ),
                    'community'   => __( 'Community & Social Services', 'faithfulwitness' ),
                ],
                'default_value' => 'community',
                'allow_null'    => 0,
                'required'      => 1,
            ],
            [
                'key'          => 'field_fw_support_org_name',
                'label'        => __( 'Organization Name', 'faithfulwitness' ),
                'name'         => 'fw_support_org_name',
                'type'         => 'text',
                'instructions' => __( 'Full legal or public-facing name of the organization.', 'faithfulwitness' ),
                'required'     => 1,
            ],
            [
                'key'          => 'field_fw_support_description',
                'label'        => __( 'Service Description', 'faithfulwitness' ),
                'name'         => 'fw_support_description',
                'type'         => 'textarea',
                'instructions' => __( 'Brief description of the services offered (2–4 sentences).', 'faithfulwitness' ),
                'rows'         => 4,
            ],
            [
                'key'          => 'field_fw_support_area',
                'label'        => __( 'Service Area', 'faithfulwitness' ),
                'name'         => 'fw_support_area',
                'type'         => 'text',
                'instructions' => __( 'City, county, state, or region served. E.g. "Chicago Metro Area" or "Nationwide".', 'faithfulwitness' ),
            ],
            [
                'key'          => 'field_fw_support_phone',
                'label'        => __( 'Phone Number', 'faithfulwitness' ),
                'name'         => 'fw_support_phone',
                'type'         => 'text',
                'instructions' => __( 'Include country code for international numbers.', 'faithfulwitness' ),
            ],
            [
                'key'          => 'field_fw_support_email',
                'label'        => __( 'Contact Email', 'faithfulwitness' ),
                'name'         => 'fw_support_email',
                'type'         => 'email',
            ],
            [
                'key'          => 'field_fw_support_website',
                'label'        => __( 'Website URL', 'faithfulwitness' ),
                'name'         => 'fw_support_website',
                'type'         => 'url',
                'instructions' => __( 'Full URL including https://', 'faithfulwitness' ),
            ],
            [
                'key'          => 'field_fw_support_legal_disclaimer',
                'label'        => __( 'Show Legal Disclaimer', 'faithfulwitness' ),
                'name'         => 'fw_support_legal_disclaimer',
                'type'         => 'true_false',
                'instructions' => __( 'Enable for Legal Services entries. Displays a "not legal advice" disclaimer alongside this listing.', 'faithfulwitness' ),
                'default_value'=> 0,
                'ui'           => 1,
                'ui_on_text'   => __( 'Yes', 'faithfulwitness' ),
                'ui_off_text'  => __( 'No', 'faithfulwitness' ),
            ],
        ],
        'location' => [
            [ [ 'param' => 'post_type', 'operator' => '==', 'value' => 'fw_support_entry' ] ],
        ],
        'menu_order' => 0,
        'style'      => 'default',
    ] );
}

// ============================================================
// RELABEL "Excerpt" → "Short Description" in editors
// ============================================================
add_action( 'admin_head', 'fw_relabel_excerpt' );
function fw_relabel_excerpt() {
    $screen = get_current_screen();
    if ( ! $screen ) return;
    if ( ! in_array( $screen->post_type, [ 'fw_resource', 'fw_organizing_group' ], true ) ) return;
    ?>
    <script>
    document.addEventListener('DOMContentLoaded', function() {
        var excerptLabel = document.querySelector('#postexcerpt h2, #postexcerpt .hndle');
        if (excerptLabel) excerptLabel.textContent = 'Short Description';
        var excerptHelp  = document.querySelector('#excerpt-fullscreen-save-wrapper, .editor-post-excerpt__title');
        if (excerptHelp) excerptHelp.textContent = 'Short Description';
    });
    </script>
    <?php
}
