<?php
/**
 * Faithful Witness — Custom Admin Menu
 *
 * Adds a "Faithful Witness" top-level menu in the WordPress sidebar
 * with quick links to the most common content management tasks.
 *
 * ADMIN NOTE: This file controls the admin sidebar menu shortcuts.
 * Do not edit this file. Content is managed via the admin forms.
 */

if ( ! defined( 'ABSPATH' ) ) exit;

// ============================================================
// REGISTER THE TOP-LEVEL MENU
// ============================================================
add_action( 'admin_menu', 'fw_register_admin_menu' );
function fw_register_admin_menu() {
    // Top-level dashboard page
    add_menu_page(
        __( 'Faithful Witness', 'faithfulwitness' ),
        __( 'Faithful Witness', 'faithfulwitness' ),
        'edit_posts',
        'faithfulwitness-hub',
        'fw_admin_dashboard_page',
        fw_admin_menu_icon(),
        3 // position — near top of sidebar
    );

    // Dashboard (same as parent)
    add_submenu_page(
        'faithfulwitness-hub',
        __( 'Dashboard', 'faithfulwitness' ),
        __( 'Dashboard', 'faithfulwitness' ),
        'edit_posts',
        'faithfulwitness-hub',
        'fw_admin_dashboard_page'
    );

    // Add a Resource
    add_submenu_page(
        'faithfulwitness-hub',
        __( 'Add a Resource', 'faithfulwitness' ),
        __( '+ Add a Resource', 'faithfulwitness' ),
        'publish_posts',
        'fw-add-resource',
        'fw_admin_redirect_page'
    );

    // Add an Event
    add_submenu_page(
        'faithfulwitness-hub',
        __( 'Add an Event', 'faithfulwitness' ),
        __( '+ Add an Event', 'faithfulwitness' ),
        'publish_posts',
        'fw-add-event',
        'fw_admin_redirect_page'
    );

    // Add a Media Hit
    add_submenu_page(
        'faithfulwitness-hub',
        __( 'Add a Media Hit', 'faithfulwitness' ),
        __( '+ Add a Media Hit', 'faithfulwitness' ),
        'publish_posts',
        'fw-add-media-hit',
        'fw_admin_redirect_page'
    );

    // Add a Story
    add_submenu_page(
        'faithfulwitness-hub',
        __( 'Add a Story', 'faithfulwitness' ),
        __( '+ Add a Story', 'faithfulwitness' ),
        'publish_posts',
        'fw-add-story',
        'fw_admin_redirect_page'
    );

    // Update Network Partners
    add_submenu_page(
        'faithfulwitness-hub',
        __( 'Network Partners', 'faithfulwitness' ),
        __( 'Network Partners', 'faithfulwitness' ),
        'edit_posts',
        'fw-partners',
        'fw_admin_redirect_page'
    );

    // Admin Guides
    add_submenu_page(
        'faithfulwitness-hub',
        __( 'Admin Guides', 'faithfulwitness' ),
        __( 'Admin Guides', 'faithfulwitness' ),
        'edit_posts',
        'fw-admin-guides',
        'fw_admin_redirect_page'
    );
}

// ============================================================
// HANDLE REDIRECTS FOR SHORTCUT SUBMENUS
// ============================================================
add_action( 'admin_init', 'fw_handle_admin_redirects' );
function fw_handle_admin_redirects() {
    if ( ! isset( $_GET['page'] ) ) return;

    $redirects = [
        'fw-add-resource'  => admin_url( 'post-new.php?post_type=fw_resource' ),
        'fw-add-event'     => admin_url( 'post-new.php?post_type=fw_event' ),
        'fw-add-media-hit' => admin_url( 'post-new.php?post_type=fw_media_hit' ),
        'fw-add-story'     => admin_url( 'post-new.php?post_type=post' ),
        'fw-partners'      => admin_url( 'edit.php?post_type=fw_organizing_group' ),
        'fw-admin-guides'  => fw_get_admin_guide_url(),
    ];

    $page = sanitize_key( $_GET['page'] );
    if ( isset( $redirects[ $page ] ) ) {
        wp_safe_redirect( $redirects[ $page ] );
        exit;
    }
}

/** Get the URL of the admin guide index. */
function fw_get_admin_guide_url() {
    $guide = get_page_by_path( 'admin-guide-content-management', OBJECT, 'page' );
    return $guide ? get_edit_post_link( $guide->ID ) : admin_url( 'edit.php?post_type=page&s=Admin+Guide' );
}

/** Callback for redirect submenus — never actually renders. */
function fw_admin_redirect_page() {}

// ============================================================
// FAITHFUL WITNESS DASHBOARD PAGE
// ============================================================
function fw_admin_dashboard_page() {
    $tasks = [
        [
            'title' => __( 'Add a Resource',    'faithfulwitness' ),
            'desc'  => __( 'Guides, toolkits, articles, and prayer resources for the library.', 'faithfulwitness' ),
            'url'   => admin_url( 'post-new.php?post_type=fw_resource' ),
            'icon'  => '📄',
            'color' => '#1B4F72',
        ],
        [
            'title' => __( 'Add an Event',      'faithfulwitness' ),
            'desc'  => __( 'Prayer gatherings, KYR trainings, court accompaniment, webinars.', 'faithfulwitness' ),
            'url'   => admin_url( 'post-new.php?post_type=fw_event' ),
            'icon'  => '📅',
            'color' => '#1A5A6A',
        ],
        [
            'title' => __( 'Add a Media Hit',   'faithfulwitness' ),
            'desc'  => __( 'Press coverage and news articles about Faithful Witness.', 'faithfulwitness' ),
            'url'   => admin_url( 'post-new.php?post_type=fw_media_hit' ),
            'icon'  => '📰',
            'color' => '#D4750A',
        ],
        [
            'title' => __( 'Add a Story',       'faithfulwitness' ),
            'desc'  => __( 'Stories from churches, families, and leaders in the field.', 'faithfulwitness' ),
            'url'   => admin_url( 'post-new.php?post_type=post' ),
            'icon'  => '✍️',
            'color' => '#1B4F72',
        ],
        [
            'title' => __( 'Network Partners',  'faithfulwitness' ),
            'desc'  => __( 'Manage partner organizations and their map pins.', 'faithfulwitness' ),
            'url'   => admin_url( 'edit.php?post_type=fw_organizing_group' ),
            'icon'  => '🗺️',
            'color' => '#1A5A6A',
        ],
        [
            'title' => __( 'All Resources',     'faithfulwitness' ),
            'desc'  => __( 'View and edit all resources in the library.', 'faithfulwitness' ),
            'url'   => admin_url( 'edit.php?post_type=fw_resource' ),
            'icon'  => '📚',
            'color' => '#D4750A',
        ],
    ];

    // Add Homepage Settings link if ACF options page exists
    $homepage_url = function_exists( 'acf_add_options_page' )
        ? admin_url( 'admin.php?page=acf-options-homepage-settings' )
        : admin_url( 'customize.php' );
    ?>
    <div class="wrap fw-admin-dashboard">
        <h1 style="display:flex;align-items:center;gap:12px;margin-bottom:24px;">
            <span style="font-size:28px;">🕊️</span>
            <?php esc_html_e( 'Faithful Witness — Content Dashboard', 'faithfulwitness' ); ?>
        </h1>

        <?php if ( ! function_exists( 'acf_add_local_field_group' ) ) : ?>
        <div class="notice notice-warning inline" style="margin-bottom:20px;">
            <p>
                <strong><?php esc_html_e( 'Tip:', 'faithfulwitness' ); ?></strong>
                <?php esc_html_e( 'Install ', 'faithfulwitness' ); ?>
                <a href="<?php echo esc_url( admin_url( 'plugin-install.php?s=advanced+custom+fields&tab=search&type=term' ) ); ?>">
                    <?php esc_html_e( 'Advanced Custom Fields (free)', 'faithfulwitness' ); ?>
                </a>
                <?php esc_html_e( 'for cleaner, guided content editing forms.', 'faithfulwitness' ); ?>
            </p>
        </div>
        <?php endif; ?>

        <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:16px;max-width:900px;">
            <?php foreach ( $tasks as $task ) : ?>
            <a href="<?php echo esc_url( $task['url'] ); ?>"
               style="display:flex;flex-direction:column;gap:8px;padding:20px;background:#fff;border:1px solid #ddd;border-radius:8px;text-decoration:none;color:inherit;transition:box-shadow 0.15s;"
               onmouseover="this.style.boxShadow='0 4px 16px rgba(0,0,0,0.12)'"
               onmouseout="this.style.boxShadow='none'">
                <span style="font-size:28px;line-height:1;"><?php echo esc_html( $task['icon'] ); ?></span>
                <strong style="font-size:15px;color:<?php echo esc_attr( $task['color'] ); ?>;"><?php echo esc_html( $task['title'] ); ?></strong>
                <span style="font-size:13px;color:#666;line-height:1.4;"><?php echo esc_html( $task['desc'] ); ?></span>
            </a>
            <?php endforeach; ?>

            <a href="<?php echo esc_url( $homepage_url ); ?>"
               style="display:flex;flex-direction:column;gap:8px;padding:20px;background:#1B4F72;border:1px solid #1B4F72;border-radius:8px;text-decoration:none;color:#fff;"
               onmouseover="this.style.opacity='0.9'"
               onmouseout="this.style.opacity='1'">
                <span style="font-size:28px;line-height:1;">🏠</span>
                <strong style="font-size:15px;"><?php esc_html_e( 'Homepage Settings', 'faithfulwitness' ); ?></strong>
                <span style="font-size:13px;opacity:0.85;line-height:1.4;"><?php esc_html_e( 'Update the campaign section, hero text, and partner logos.', 'faithfulwitness' ); ?></span>
            </a>
        </div>

        <hr style="margin:32px 0;">

        <h2><?php esc_html_e( 'Recent Activity', 'faithfulwitness' ); ?></h2>
        <table class="wp-list-table widefat fixed striped" style="max-width:700px;">
            <thead>
                <tr>
                    <th><?php esc_html_e( 'Content', 'faithfulwitness' ); ?></th>
                    <th><?php esc_html_e( 'Type', 'faithfulwitness' ); ?></th>
                    <th><?php esc_html_e( 'Date', 'faithfulwitness' ); ?></th>
                    <th><?php esc_html_e( 'Actions', 'faithfulwitness' ); ?></th>
                </tr>
            </thead>
            <tbody>
                <?php
                $recent = get_posts( [
                    'post_type'   => [ 'fw_resource', 'fw_event', 'fw_media_hit', 'post', 'fw_organizing_group' ],
                    'post_status' => [ 'publish', 'draft' ],
                    'numberposts' => 8,
                    'orderby'     => 'modified',
                    'order'       => 'DESC',
                ] );

                $type_labels = [
                    'fw_resource'        => __( 'Resource',    'faithfulwitness' ),
                    'fw_event'           => __( 'Event',       'faithfulwitness' ),
                    'fw_media_hit'       => __( 'Press Hit',   'faithfulwitness' ),
                    'post'               => __( 'Story',       'faithfulwitness' ),
                    'fw_organizing_group'=> __( 'Partner',     'faithfulwitness' ),
                ];

                foreach ( $recent as $item ) :
                    $type_label = $type_labels[ $item->post_type ] ?? $item->post_type;
                    $status_badge = $item->post_status === 'draft' ? ' <em style="color:#999;">(draft)</em>' : '';
                ?>
                <tr>
                    <td><strong><?php echo esc_html( get_the_title( $item ) ); ?></strong><?php echo $status_badge; // phpcs:ignore ?></td>
                    <td><?php echo esc_html( $type_label ); ?></td>
                    <td><?php echo esc_html( get_the_modified_date( 'M j, Y', $item ) ); ?></td>
                    <td>
                        <a href="<?php echo esc_url( get_edit_post_link( $item ) ); ?>"><?php esc_html_e( 'Edit', 'faithfulwitness' ); ?></a>
                        <?php if ( $item->post_status === 'publish' && get_permalink( $item ) ) : ?>
                        · <a href="<?php echo esc_url( get_permalink( $item ) ); ?>" target="_blank"><?php esc_html_e( 'View', 'faithfulwitness' ); ?></a>
                        <?php endif; ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>

        <hr style="margin:32px 0;">
        <p style="color:#666;font-size:13px;">
            <?php esc_html_e( 'Need help? Read the ', 'faithfulwitness' ); ?>
            <a href="<?php echo esc_url( fw_get_admin_guide_url() ); ?>"><?php esc_html_e( 'Admin Guide', 'faithfulwitness' ); ?></a>
            <?php esc_html_e( ' for step-by-step instructions.', 'faithfulwitness' ); ?>
        </p>
    </div>
    <?php
}

// ============================================================
// MENU ICON — custom SVG cross/dove
// ============================================================
function fw_admin_menu_icon() {
    // Base64 encoded SVG: simple dove/peace symbol
    $svg = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor"><path d="M10 2a8 8 0 100 16A8 8 0 0010 2zm0 14a6 6 0 110-12 6 6 0 010 12zm-1-9h2v4H9V7zm0 5h2v2H9v-2z"/></svg>';
    return 'data:image/svg+xml;base64,' . base64_encode( $svg );
}
