<?php
/**
 * Template Name: Find Support
 *
 * WHAT THIS PAGE DOES:
 *   Landing page for the Find Support directory. Displays four pathway cards
 *   (Basic Needs, Legal Services, Spiritual Support, Community Services) each
 *   linking to sub-pages that list support entries filtered by type.
 *
 * HOW TO MANAGE CONTENT (no code editing required):
 *   - Support entries are added via Posts → Find Support in the admin
 *   - Each card links to a child page with the template "Find Support — Section"
 *   - Hero text is edited via Pages → Find Support → edit (ACF hero fields)
 *
 * DO NOT EDIT THIS FILE to change support entry content.
 */

get_header();

$hero_eyebrow  = get_field( 'fw_page_hero_eyebrow' )  ?: __( 'We Are With You', 'faithfulwitness' );
$hero_title    = get_field( 'fw_page_hero_title' )    ?: __( 'Find Support', 'faithfulwitness' );
$hero_subtitle = get_field( 'fw_page_hero_subtitle' ) ?: __( 'Whether you need practical help, legal guidance, or a caring community — you do not have to face this alone.', 'faithfulwitness' );

$pathways = [
    [
        'type'  => 'basic_needs',
        'title' => __( 'Basic Needs', 'faithfulwitness' ),
        'desc'  => __( 'Food, housing, clothing, and emergency assistance organizations serving immigrants and families in need.', 'faithfulwitness' ),
        'icon'  => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" width="32" height="32"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/></svg>',
        'slug'  => 'basic-needs',
        'color' => 'var(--color-teal)',
    ],
    [
        'type'  => 'legal',
        'title' => __( 'Legal Services', 'faithfulwitness' ),
        'desc'  => __( 'Accredited immigration attorneys and legal aid organizations providing consultations, representation, and Know Your Rights support.', 'faithfulwitness' ),
        'icon'  => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" width="32" height="32"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>',
        'slug'  => 'legal-services',
        'color' => 'var(--color-primary)',
    ],
    [
        'type'  => 'spiritual',
        'title' => __( 'Spiritual & Pastoral Support', 'faithfulwitness' ),
        'desc'  => __( 'Faith communities, chaplains, and pastoral care resources for immigrants, families under stress, and congregations walking alongside them.', 'faithfulwitness' ),
        'icon'  => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" width="32" height="32"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/></svg>',
        'slug'  => 'spiritual-support',
        'color' => 'var(--color-accent)',
    ],
    [
        'type'  => 'community',
        'title' => __( 'Community Services', 'faithfulwitness' ),
        'desc'  => __( 'Social services, mental health resources, educational programs, and community organizations serving immigrants and their families.', 'faithfulwitness' ),
        'icon'  => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" width="32" height="32"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>',
        'slug'  => 'community-services',
        'color' => 'var(--color-teal)',
    ],
];
?>

<!-- Hero -->
<section class="find-support-hero" id="find-support-top">
    <div class="container">
        <span class="hero__eyebrow" style="color:var(--color-accent-light);"><?php echo esc_html( $hero_eyebrow ); ?></span>
        <h1><?php echo esc_html( $hero_title ); ?></h1>
        <p><?php echo esc_html( $hero_subtitle ); ?></p>
    </div>
</section>

<!-- Support Pathway Cards -->
<section class="find-support-pathways section" id="support-pathways">
    <div class="container">
        <div class="section-header section-header--center">
            <span class="eyebrow"><?php esc_html_e( 'Choose a Category', 'faithfulwitness' ); ?></span>
            <h2><?php esc_html_e( 'What kind of support do you need?', 'faithfulwitness' ); ?></h2>
        </div>

        <div class="support-pathway-grid">
            <?php foreach ( $pathways as $pathway ) :
                // Attempt to find child page with matching slug
                $child = get_page_by_path( get_post_field( 'post_name', get_the_ID() ) . '/' . $pathway['slug'] );
                $url   = $child ? get_permalink( $child ) : home_url( '/find-support/' . $pathway['slug'] );
            ?>
            <a href="<?php echo esc_url( $url ); ?>" class="support-pathway-card">
                <div class="support-pathway-card__icon" aria-hidden="true" style="color:<?php echo esc_attr( $pathway['color'] ); ?>;">
                    <?php echo $pathway['icon']; // pre-sanitized SVG ?>
                </div>
                <h3 class="support-pathway-card__title"><?php echo esc_html( $pathway['title'] ); ?></h3>
                <p class="support-pathway-card__desc"><?php echo esc_html( $pathway['desc'] ); ?></p>
                <span class="support-pathway-card__link"><?php esc_html_e( 'Find resources →', 'faithfulwitness' ); ?></span>
            </a>
            <?php endforeach; ?>
        </div>
    </div>
</section>

<!-- Quick stats / totals -->
<?php
$total_entries = wp_count_posts( 'fw_support_entry' )->publish;
if ( $total_entries > 0 ) : ?>
<section class="section section--alt" id="support-overview">
    <div class="container" style="text-align:center;">
        <p style="font-size:var(--text-lg);color:var(--color-text-muted);">
            <?php printf(
                esc_html( _n(
                    'Currently listing %s support organization.',
                    'Currently listing %s support organizations.',
                    $total_entries,
                    'faithfulwitness'
                ) ),
                '<strong>' . number_format_i18n( $total_entries ) . '</strong>'
            ); ?>
        </p>
        <p style="margin-top:var(--space-4);color:var(--color-text-muted);font-size:var(--text-sm);">
            <?php esc_html_e( 'Know of an organization we should add? Contact us.', 'faithfulwitness' ); ?>
        </p>
    </div>
</section>
<?php endif; ?>

<!-- Legal Disclaimer -->
<section class="section" id="find-support-disclaimer">
    <div class="container container--narrow">
        <?php fw_render_legal_disclaimer(); ?>
    </div>
</section>

<?php get_footer();
