<?php
/**
 * Template Name: About
 *
 * WHAT THIS PAGE DOES:
 *   The About page for Faithful Witness. Displays Vision, Mission, Distinctives,
 *   Policy Positions, Partner organizations, a Scripture anchor, and a contact section.
 *
 * HOW TO MANAGE CONTENT (no code editing required):
 *   - Vision, mission, and distinctives are edited via Pages → About → edit
 *     (ACF fields in the "About — Content" box)
 *   - Partner organizations are pulled from the Network (fw_organizing_group)
 *   - Scripture pullquote is set via ACF field on this page
 *
 * DO NOT EDIT THIS FILE to change page content. Only edit for layout changes.
 */

get_header();

$hero_eyebrow  = get_field( 'fw_page_hero_eyebrow' )  ?: __( 'Who We Are', 'faithfulwitness' );
$hero_title    = get_field( 'fw_page_hero_title' )    ?: __( 'About Faithful Witness', 'faithfulwitness' );
$hero_subtitle = get_field( 'fw_page_hero_subtitle' ) ?: __( 'A Gospel-centered campaign forming the Church for courageous, nonviolent engagement on immigration.', 'faithfulwitness' );

$vision     = get_field( 'fw_about_vision' )
    ?: get_theme_mod( 'fw_about_vision', __( 'A Church that embodies the welcome of Christ — courageous, nonviolent, and rooted in love — at every table where the future of immigrants and refugees is being decided.', 'faithfulwitness' ) );

$mission    = get_field( 'fw_about_mission' )
    ?: get_theme_mod( 'fw_about_mission', __( 'Faithful Witness forms and mobilizes faith communities to accompany immigrants, advocate for just policies, and bear witness to the Gospel at the intersection of faith and immigration.', 'faithfulwitness' ) );

$distinctives = get_field( 'fw_about_distinctives' ) ?: '';

$nat_policies = get_field( 'fw_about_national_policies' ) ?: '';
$loc_policies = get_field( 'fw_about_local_policies' )    ?: '';

$scripture_text = get_field( 'fw_about_scripture_text' )
    ?: get_theme_mod( 'fw_about_scripture_text', __( 'When a foreigner resides among you in your land, do not mistreat them. The foreigner residing among you must be treated as your native-born.', 'faithfulwitness' ) );
$scripture_ref  = get_field( 'fw_about_scripture_ref' )
    ?: get_theme_mod( 'fw_about_scripture_ref', __( 'Leviticus 19:33–34', 'faithfulwitness' ) );
?>

<!-- Hero -->
<section class="about-hero" id="about-top">
    <div class="container">
        <span class="hero__eyebrow" style="color:var(--color-accent-light);"><?php echo esc_html( $hero_eyebrow ); ?></span>
        <h1><?php echo esc_html( $hero_title ); ?></h1>
        <p><?php echo esc_html( $hero_subtitle ); ?></p>
    </div>
</section>

<!-- Vision & Mission -->
<section class="about-vision-mission section" id="vision-mission">
    <div class="container container--narrow">
        <div class="about-vm-block">
            <span class="eyebrow"><?php esc_html_e( 'Our Vision', 'faithfulwitness' ); ?></span>
            <p class="about-vm-text"><?php echo esc_html( $vision ); ?></p>
        </div>
        <div class="about-vm-block" style="margin-top:var(--space-10);">
            <span class="eyebrow"><?php esc_html_e( 'Our Mission', 'faithfulwitness' ); ?></span>
            <p class="about-vm-text"><?php echo esc_html( $mission ); ?></p>
        </div>
    </div>
</section>

<!-- Distinctives -->
<?php if ( $distinctives ) : ?>
<section class="about-distinctives section section--alt" id="distinctives">
    <div class="container container--narrow">
        <span class="eyebrow"><?php esc_html_e( 'Our Distinctives', 'faithfulwitness' ); ?></span>
        <h2><?php esc_html_e( 'What Makes Faithful Witness Different', 'faithfulwitness' ); ?></h2>
        <div class="entry-content"><?php echo wp_kses_post( $distinctives ); ?></div>
    </div>
</section>
<?php endif; ?>

<!-- Policy Positions -->
<?php if ( $nat_policies || $loc_policies ) : ?>
<section class="about-policies section" id="policy-positions">
    <div class="container container--narrow">
        <span class="eyebrow"><?php esc_html_e( 'Where We Stand', 'faithfulwitness' ); ?></span>
        <h2><?php esc_html_e( 'Policy Positions', 'faithfulwitness' ); ?></h2>

        <?php if ( $nat_policies ) : ?>
        <div class="about-policy-block">
            <h3><?php esc_html_e( 'National Policies', 'faithfulwitness' ); ?></h3>
            <div class="entry-content"><?php echo wp_kses_post( $nat_policies ); ?></div>
        </div>
        <?php endif; ?>

        <?php if ( $loc_policies ) : ?>
        <div class="about-policy-block" style="margin-top:var(--space-8);">
            <h3><?php esc_html_e( 'Local Policies', 'faithfulwitness' ); ?></h3>
            <div class="entry-content"><?php echo wp_kses_post( $loc_policies ); ?></div>
        </div>
        <?php endif; ?>
    </div>
</section>
<?php endif; ?>

<!-- Scripture Anchor -->
<section class="about-scripture" id="about-scripture">
    <div class="container">
        <p class="formation-pullquote__text"><?php echo esc_html( $scripture_text ); ?></p>
        <span class="formation-pullquote__ref"><?php echo esc_html( $scripture_ref ); ?></span>
    </div>
</section>

<!-- Partner Organizations -->
<section class="about-partners section section--alt" id="about-partners">
    <div class="container">
        <div class="section-header section-header--center">
            <span class="eyebrow"><?php esc_html_e( 'Coalition', 'faithfulwitness' ); ?></span>
            <h2><?php esc_html_e( 'Our Partner Organizations', 'faithfulwitness' ); ?></h2>
            <p><?php esc_html_e( 'Faithful Witness is a coalition of faith-rooted organizations committed to the dignity and welcome of immigrants.', 'faithfulwitness' ); ?></p>
        </div>

        <?php
        $partners = get_posts( [
            'post_type'      => 'fw_organizing_group',
            'post_status'    => 'publish',
            'posts_per_page' => 12,
            'orderby'        => 'title',
            'order'          => 'ASC',
        ] );
        if ( ! empty( $partners ) ) : ?>
        <div class="about-partners-grid">
            <?php foreach ( $partners as $partner ) :
                $website = get_post_meta( $partner->ID, 'fw_website_url', true );
                $city    = get_post_meta( $partner->ID, 'fw_city', true );
                $state   = get_post_meta( $partner->ID, 'fw_state_abbr', true );
                $loc     = array_filter( [ $city, $state ] );
            ?>
            <div class="about-partner-card">
                <?php if ( has_post_thumbnail( $partner ) ) : ?>
                <div class="about-partner-card__logo">
                    <?php echo get_the_post_thumbnail( $partner, 'fw-thumb', [ 'loading' => 'lazy' ] ); ?>
                </div>
                <?php endif; ?>
                <h3 class="about-partner-card__name">
                    <?php if ( $website ) : ?>
                    <a href="<?php echo esc_url( $website ); ?>" target="_blank" rel="noopener noreferrer">
                        <?php echo esc_html( get_the_title( $partner ) ); ?>
                    </a>
                    <?php else : ?>
                    <?php echo esc_html( get_the_title( $partner ) ); ?>
                    <?php endif; ?>
                </h3>
                <?php if ( ! empty( $loc ) ) : ?>
                <p class="about-partner-card__location"><?php echo esc_html( implode( ', ', $loc ) ); ?></p>
                <?php endif; ?>
            </div>
            <?php endforeach; ?>
        </div>
        <?php else : ?>
        <p style="text-align:center;color:var(--color-text-muted);padding:3rem 0;">
            <?php esc_html_e( 'Partner organizations coming soon.', 'faithfulwitness' ); ?>
        </p>
        <?php endif; ?>

        <div style="text-align:center;margin-top:var(--space-10);">
            <a href="<?php echo esc_url( home_url( '/network' ) ); ?>" class="btn btn--outline btn--lg">
                <?php esc_html_e( 'View the Full Network Map', 'faithfulwitness' ); ?>
            </a>
        </div>
    </div>
</section>

<!-- Contact / Page content from editor -->
<?php if ( have_posts() ) : while ( have_posts() ) : the_post(); ?>
<?php if ( $content = get_the_content() ) : ?>
<section class="section" id="about-contact">
    <div class="container container--narrow">
        <div class="entry-content"><?php the_content(); ?></div>
    </div>
</section>
<?php endif; endwhile; endif; ?>

<?php get_footer();
