<?php
/**
 * Template Name: Take Action
 *
 * WHAT THIS PAGE DOES:
 *   A campaign-action landing page with three paths (Join / Attend / Advocate),
 *   an active initiatives section pulled from the fw_initiative post type,
 *   and a sign-up/pledge form.
 *
 * HOW TO MANAGE CONTENT (no code editing required):
 *   - Initiatives shown here are pulled automatically from Posts → Initiatives
 *   - To feature a specific initiative, set its status to "Active" in the Initiative Details box
 *   - The sign-up form links to the Mailchimp join link (edit the URL in this file if it changes)
 *
 * TO UPDATE THE JOIN LINK:
 *   Search this file for "mailchi.mp" and replace with the updated campaign signup URL.
 *
 * DO NOT EDIT THIS FILE to change initiative content. Only edit for layout/structural changes.
 */

get_header();

// Read page-level ACF hero fields (edit via Pages → Take Action → edit)
$hero_eyebrow  = get_field( 'fw_page_hero_eyebrow' )  ?: __( 'Get Involved', 'faithfulwitness' );
$hero_title    = get_field( 'fw_page_hero_title' )    ?: __( 'Faithful witness starts here. Choose your path.', 'faithfulwitness' );
$hero_subtitle = get_field( 'fw_page_hero_subtitle' ) ?: __( "Whether you're just beginning to explore, ready to organize, or navigating the system yourself — there is a place for you here.", 'faithfulwitness' );
?>

<!-- Bold Hero -->
<section class="take-action-hero" id="take-action-top">
    <div class="container">
        <span class="hero__eyebrow" style="color:var(--color-accent-light);"><?php echo esc_html( $hero_eyebrow ); ?></span>
        <h1><?php echo esc_html( $hero_title ); ?></h1>
        <p style="font-size:var(--text-xl);opacity:.9;max-width:580px;margin:0 auto;"><?php echo esc_html( $hero_subtitle ); ?></p>
    </div>
</section>

<!-- Three Audience Action Cards -->
<section class="action-cards-section" id="choose-path">
    <div class="container">
        <div class="section-header section-header--center">
            <span class="eyebrow"><?php esc_html_e( 'Where Do You Begin?', 'faithfulwitness' ); ?></span>
            <h2><?php esc_html_e( 'Find Your Starting Point', 'faithfulwitness' ); ?></h2>
        </div>

        <?php
        $acf_cards = [
            [
                'audience'  => get_field( 'fw_ta_card1_audience' ) ?: __( "I'm uncertain", 'faithfulwitness' ),
                'title'     => get_field( 'fw_ta_card1_title' )    ?: __( 'Start by learning', 'faithfulwitness' ),
                'desc'      => get_field( 'fw_ta_card1_desc' )     ?: __( "You sense something is wrong but aren't sure what faithful engagement looks like. Start with our resources — guides, articles, and tools to help you understand immigration through a Gospel lens.", 'faithfulwitness' ),
                'btn_label' => get_field( 'fw_ta_card1_btn_label' ) ?: __( 'Browse Resources', 'faithfulwitness' ),
                'btn_url'   => get_field( 'fw_ta_card1_btn_url' )   ?: home_url( '/resources' ),
                'btn_class' => 'btn--outline',
                'card_style'=> '',
                'icon_style'=> '',
                'icon'      => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" width="28" height="28"><circle cx="12" cy="12" r="10"/><path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>',
            ],
            [
                'audience'  => get_field( 'fw_ta_card2_audience' ) ?: __( "I'm ready to organize", 'faithfulwitness' ),
                'title'     => get_field( 'fw_ta_card2_title' )    ?: __( 'Find your local group', 'faithfulwitness' ),
                'desc'      => get_field( 'fw_ta_card2_desc' )     ?: __( "You're a church leader, pastor, or congregation ready to act. Connect with other faithful witnesses in your area, access organizing toolkits, and join the national network.", 'faithfulwitness' ),
                'btn_label' => get_field( 'fw_ta_card2_btn_label' ) ?: __( 'Find a Group Near Me', 'faithfulwitness' ),
                'btn_url'   => get_field( 'fw_ta_card2_btn_url' )   ?: home_url( '/network' ),
                'btn_class' => 'btn--primary',
                'card_style'=> 'border-color:var(--color-primary);background:rgba(27,79,114,0.02);',
                'icon_style'=> 'background:rgba(27,79,114,0.12);',
                'icon'      => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" width="28" height="28"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>',
            ],
            [
                'audience'  => get_field( 'fw_ta_card3_audience' ) ?: __( "I'm directly affected", 'faithfulwitness' ),
                'title'     => get_field( 'fw_ta_card3_title' )    ?: __( 'Connect with support', 'faithfulwitness' ),
                'desc'      => get_field( 'fw_ta_card3_desc' )     ?: __( 'You or someone you love is navigating the immigration system right now. Access practical Know Your Rights information, find a local group, and connect with a community that will stand with you.', 'faithfulwitness' ),
                'btn_label' => get_field( 'fw_ta_card3_btn_label' ) ?: __( 'Know Your Rights', 'faithfulwitness' ),
                'btn_url'   => get_field( 'fw_ta_card3_btn_url' )   ?: home_url( '/know-your-rights' ),
                'btn_class' => 'btn--teal',
                'card_style'=> '',
                'icon_style'=> '',
                'icon'      => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" width="28" height="28"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/></svg>',
            ],
        ];
        ?>
        <div class="action-cards-grid">
            <?php foreach ( $acf_cards as $card ) : ?>
            <div class="action-card"<?php echo $card['card_style'] ? ' style="' . esc_attr( $card['card_style'] ) . '"' : ''; ?>>
                <div class="action-card__icon"<?php echo $card['icon_style'] ? ' style="' . esc_attr( $card['icon_style'] ) . '"' : ''; ?> aria-hidden="true">
                    <?php echo $card['icon']; // pre-sanitized SVG ?>
                </div>
                <span class="action-card__audience"><?php echo esc_html( $card['audience'] ); ?></span>
                <h2 class="action-card__title"><?php echo esc_html( $card['title'] ); ?></h2>
                <p class="action-card__desc"><?php echo esc_html( $card['desc'] ); ?></p>
                <div class="action-card__cta">
                    <a href="<?php echo esc_url( $card['btn_url'] ); ?>" class="btn <?php echo esc_attr( $card['btn_class'] ); ?> btn--lg" style="width:100%;justify-content:center;">
                        <?php echo esc_html( $card['btn_label'] ); ?>
                    </a>
                </div>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
</section>

<?php fw_render_mailchimp_signup_section(); ?>

<!-- Current Campaigns -->
<section class="campaigns-section" id="campaigns">
    <div class="container">
        <div class="section-header">
            <span class="eyebrow"><?php esc_html_e( 'Right Now', 'faithfulwitness' ); ?></span>
            <h2><?php esc_html_e( 'Current Campaigns', 'faithfulwitness' ); ?></h2>
            <p><?php esc_html_e( 'These are the active campaigns where your participation makes a difference.', 'faithfulwitness' ); ?></p>
        </div>

        <?php
        $initiatives = get_posts( [
            'post_type'      => 'fw_initiative',
            'post_status'    => 'publish',
            'posts_per_page' => 6,
            'orderby'        => 'date',
            'order'          => 'DESC',
        ] );

        if ( ! empty( $initiatives ) ) : ?>
        <div class="campaigns-list">
            <?php foreach ( $initiatives as $init ) :
                $cta_url   = get_post_meta( $init->ID, 'fw_initiative_cta_url', true );
                $cta_label = get_post_meta( $init->ID, 'fw_initiative_cta_label', true ) ?: __( 'Take Action', 'faithfulwitness' );
            ?>
            <div class="campaign-item">
                <div>
                    <h3 class="campaign-item__title"><?php echo esc_html( get_the_title( $init ) ); ?></h3>
                    <p class="campaign-item__desc"><?php echo esc_html( wp_trim_words( get_the_excerpt( $init ), 25, '…' ) ); ?></p>
                </div>
                <a href="<?php echo esc_url( $cta_url ?: get_permalink( $init ) ); ?>" class="btn btn--primary btn--sm">
                    <?php echo esc_html( $cta_label ); ?>
                </a>
            </div>
            <?php endforeach; ?>
        </div>
        <?php else : ?>
        <p style="color:var(--color-text-muted);text-align:center;padding:3rem 0;">
            <?php esc_html_e( 'Campaigns coming soon. Check back soon!', 'faithfulwitness' ); ?>
        </p>
        <?php endif; ?>
    </div>
</section>

<?php get_footer();
